// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CORRELATE_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        prev_output_channel_V_address0,
        prev_output_channel_V_ce0,
        prev_output_channel_V_q0,
        filter_V_address0,
        filter_V_ce0,
        filter_V_q0,
        correlate_img_V_address0,
        correlate_img_V_ce0,
        correlate_img_V_we0,
        correlate_img_V_d0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] prev_output_channel_V_address0;
output   prev_output_channel_V_ce0;
input  [11:0] prev_output_channel_V_q0;
output  [3:0] filter_V_address0;
output   filter_V_ce0;
input  [11:0] filter_V_q0;
output  [5:0] correlate_img_V_address0;
output   correlate_img_V_ce0;
output   correlate_img_V_we0;
output  [11:0] correlate_img_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg prev_output_channel_V_ce0;
reg filter_V_ce0;
reg correlate_img_V_ce0;
reg correlate_img_V_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] index_fu_171_p2;
reg   [9:0] index_reg_475;
wire    ap_CS_fsm_state2;
wire   [20:0] add_ln49_fu_177_p2;
reg   [20:0] add_ln49_reg_480;
wire   [0:0] icmp_ln46_fu_165_p2;
wire   [6:0] tmp_91_fu_183_p4;
reg   [6:0] tmp_91_reg_485;
wire   [6:0] k_y_fu_215_p2;
reg   [6:0] k_y_reg_490;
wire   [0:0] tmp_92_fu_221_p3;
reg   [0:0] tmp_92_reg_495;
wire   [0:0] icmp_ln55_fu_229_p2;
reg   [0:0] icmp_ln55_reg_499;
wire   [0:0] icmp_ln55_1_fu_235_p2;
reg   [0:0] icmp_ln55_1_reg_505;
reg   [3:0] tmp_reg_511;
wire   [0:0] and_ln65_fu_269_p2;
reg   [0:0] and_ln65_reg_517;
wire    ap_CS_fsm_state3;
wire  signed [31:0] select_ln55_fu_327_p3;
reg  signed [31:0] select_ln55_reg_526;
wire    ap_CS_fsm_state4;
reg  signed [11:0] prev_output_channel_2_reg_531;
wire  signed [23:0] r_V_6_fu_454_p2;
reg  signed [23:0] r_V_6_reg_541;
wire    ap_CS_fsm_state5;
wire   [9:0] select_ln71_fu_426_p3;
wire    ap_CS_fsm_state6;
wire   [9:0] select_ln71_2_fu_446_p3;
reg   [9:0] index_0_reg_119;
reg   [20:0] phi_mul_reg_130;
reg   [9:0] phi_urem_reg_141;
reg   [9:0] phi_urem33_reg_153;
wire   [63:0] zext_ln1116_8_fu_312_p1;
wire  signed [63:0] sext_ln62_fu_334_p1;
wire   [63:0] zext_ln68_fu_400_p1;
reg   [31:0] index_filter_2_fu_72;
wire   [31:0] index_filter_fu_395_p2;
reg   [11:0] sum_V_2_fu_76;
wire   [3:0] trunc_ln50_fu_193_p1;
wire   [3:0] mul_ln50_fu_201_p1;
wire   [6:0] trunc_ln51_2_fu_211_p1;
wire   [1:0] trunc_ln51_fu_207_p1;
wire   [9:0] mul_ln50_fu_201_p2;
wire   [3:0] add_ln65_fu_251_p2;
wire   [0:0] icmp_ln65_fu_257_p2;
wire   [0:0] icmp_ln65_1_fu_263_p2;
wire   [9:0] tmp_s_fu_278_p3;
wire   [5:0] tmp_128_fu_289_p3;
wire   [10:0] zext_ln1116_7_fu_296_p1;
wire   [10:0] zext_ln1116_6_fu_285_p1;
wire   [10:0] add_ln1116_fu_300_p2;
wire   [10:0] zext_ln1116_fu_275_p1;
wire   [10:0] add_ln1116_3_fu_306_p2;
wire   [31:0] select_ln55_1_fu_320_p3;
wire   [11:0] select_ln55_4_fu_349_p3;
wire   [11:0] select_ln55_5_fu_356_p3;
wire   [15:0] lhs_V_fu_363_p3;
wire   [24:0] zext_ln728_fu_371_p1;
wire   [24:0] zext_ln703_fu_375_p1;
wire   [24:0] ret_V_fu_378_p2;
wire   [9:0] add_ln71_fu_414_p2;
wire   [0:0] icmp_ln71_fu_420_p2;
wire   [9:0] add_ln71_2_fu_434_p2;
wire   [0:0] icmp_ln71_2_fu_440_p2;
reg   [5:0] ap_NS_fsm;
wire   [9:0] mul_ln50_fu_201_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

FSRCNN_mul_mul_12CeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 24 ))
FSRCNN_mul_mul_12CeG_U56(
    .din0(prev_output_channel_2_reg_531),
    .din1(filter_V_q0),
    .dout(r_V_6_fu_454_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        index_0_reg_119 <= index_reg_475;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        index_0_reg_119 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        phi_mul_reg_130 <= add_ln49_reg_480;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_reg_130 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        phi_urem33_reg_153 <= select_ln71_fu_426_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_urem33_reg_153 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        phi_urem_reg_141 <= select_ln71_2_fu_446_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_urem_reg_141 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_165_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln49_reg_480 <= add_ln49_fu_177_p2;
        k_y_reg_490 <= k_y_fu_215_p2;
        tmp_91_reg_485 <= {{phi_mul_reg_130[20:14]}};
        tmp_92_reg_495 <= k_y_fu_215_p2[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_92_fu_221_p3 == 1'd0) & (icmp_ln46_fu_165_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        and_ln65_reg_517 <= and_ln65_fu_269_p2;
        icmp_ln55_1_reg_505 <= icmp_ln55_1_fu_235_p2;
        icmp_ln55_reg_499 <= icmp_ln55_fu_229_p2;
        tmp_reg_511 <= {{mul_ln50_fu_201_p2[9:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_92_reg_495 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        index_filter_2_fu_72 <= index_filter_fu_395_p2;
        sum_V_2_fu_76 <= {{ret_V_fu_378_p2[15:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        index_reg_475 <= index_fu_171_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        prev_output_channel_2_reg_531 <= prev_output_channel_V_q0;
        select_ln55_reg_526 <= select_ln55_fu_327_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        r_V_6_reg_541 <= r_V_6_fu_454_p2;
    end
end

always @ (*) begin
    if ((((icmp_ln46_fu_165_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_165_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        correlate_img_V_ce0 = 1'b1;
    end else begin
        correlate_img_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln65_reg_517) & (tmp_92_reg_495 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        correlate_img_V_we0 = 1'b1;
    end else begin
        correlate_img_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        filter_V_ce0 = 1'b1;
    end else begin
        filter_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        prev_output_channel_V_ce0 = 1'b1;
    end else begin
        prev_output_channel_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln46_fu_165_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((tmp_92_fu_221_p3 == 1'd1) & (icmp_ln46_fu_165_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1116_3_fu_306_p2 = (add_ln1116_fu_300_p2 + zext_ln1116_fu_275_p1);

assign add_ln1116_fu_300_p2 = (zext_ln1116_7_fu_296_p1 + zext_ln1116_6_fu_285_p1);

assign add_ln49_fu_177_p2 = (21'd1821 + phi_mul_reg_130);

assign add_ln65_fu_251_p2 = ($signed(trunc_ln50_fu_193_p1) + $signed(4'd10));

assign add_ln71_2_fu_434_p2 = (phi_urem_reg_141 + 10'd1);

assign add_ln71_fu_414_p2 = (phi_urem33_reg_153 + 10'd1);

assign and_ln65_fu_269_p2 = (icmp_ln65_fu_257_p2 & icmp_ln65_1_fu_263_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign correlate_img_V_address0 = zext_ln68_fu_400_p1;

assign correlate_img_V_d0 = {{ret_V_fu_378_p2[15:4]}};

assign filter_V_address0 = sext_ln62_fu_334_p1;

assign icmp_ln46_fu_165_p2 = ((index_0_reg_119 == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_235_p2 = ((trunc_ln51_fu_207_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_229_p2 = ((trunc_ln50_fu_193_p1 < 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_263_p2 = ((trunc_ln51_fu_207_p1 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_257_p2 = ((add_ln65_fu_251_p2 < 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln71_2_fu_440_p2 = ((add_ln71_2_fu_434_p2 < 10'd9) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_420_p2 = ((add_ln71_fu_414_p2 < 10'd3) ? 1'b1 : 1'b0);

assign index_filter_fu_395_p2 = ($signed(select_ln55_reg_526) + $signed(32'd1));

assign index_fu_171_p2 = (index_0_reg_119 + 10'd1);

assign k_y_fu_215_p2 = (tmp_91_fu_183_p4 + trunc_ln51_2_fu_211_p1);

assign lhs_V_fu_363_p3 = {{select_ln55_5_fu_356_p3}, {4'd0}};

assign mul_ln50_fu_201_p1 = mul_ln50_fu_201_p10;

assign mul_ln50_fu_201_p10 = trunc_ln50_fu_193_p1;

assign mul_ln50_fu_201_p2 = (10'd22 * mul_ln50_fu_201_p1);

assign prev_output_channel_V_address0 = zext_ln1116_8_fu_312_p1;

assign ret_V_fu_378_p2 = (zext_ln728_fu_371_p1 + zext_ln703_fu_375_p1);

assign select_ln55_1_fu_320_p3 = ((icmp_ln55_1_reg_505[0:0] === 1'b1) ? 32'd0 : index_filter_2_fu_72);

assign select_ln55_4_fu_349_p3 = ((icmp_ln55_1_reg_505[0:0] === 1'b1) ? 12'd0 : sum_V_2_fu_76);

assign select_ln55_5_fu_356_p3 = ((icmp_ln55_reg_499[0:0] === 1'b1) ? select_ln55_4_fu_349_p3 : sum_V_2_fu_76);

assign select_ln55_fu_327_p3 = ((icmp_ln55_reg_499[0:0] === 1'b1) ? select_ln55_1_fu_320_p3 : index_filter_2_fu_72);

assign select_ln71_2_fu_446_p3 = ((icmp_ln71_2_fu_440_p2[0:0] === 1'b1) ? add_ln71_2_fu_434_p2 : 10'd0);

assign select_ln71_fu_426_p3 = ((icmp_ln71_fu_420_p2[0:0] === 1'b1) ? add_ln71_fu_414_p2 : 10'd0);

assign sext_ln62_fu_334_p1 = select_ln55_fu_327_p3;

assign tmp_128_fu_289_p3 = {{tmp_reg_511}, {2'd0}};

assign tmp_91_fu_183_p4 = {{phi_mul_reg_130[20:14]}};

assign tmp_92_fu_221_p3 = k_y_fu_215_p2[32'd6];

assign tmp_s_fu_278_p3 = {{tmp_reg_511}, {6'd0}};

assign trunc_ln50_fu_193_p1 = phi_urem_reg_141[3:0];

assign trunc_ln51_2_fu_211_p1 = phi_urem33_reg_153[6:0];

assign trunc_ln51_fu_207_p1 = phi_urem33_reg_153[1:0];

assign zext_ln1116_6_fu_285_p1 = tmp_s_fu_278_p3;

assign zext_ln1116_7_fu_296_p1 = tmp_128_fu_289_p3;

assign zext_ln1116_8_fu_312_p1 = add_ln1116_3_fu_306_p2;

assign zext_ln1116_fu_275_p1 = k_y_reg_490;

assign zext_ln68_fu_400_p1 = tmp_91_reg_485;

assign zext_ln703_fu_375_p1 = $unsigned(r_V_6_reg_541);

assign zext_ln728_fu_371_p1 = lhs_V_fu_363_p3;

endmodule //CORRELATE_1
