# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/UIUC_GRAD/UIUC_ECE527/Final_project/try_block_design/try_block_design.srcs/sources_1/bd/design_1/ip/design_1_FSRCNN_0_8/design_1_FSRCNN_0_8.xci
# IP: The module: 'design_1_FSRCNN_0_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UIUC_GRAD/UIUC_ECE527/Final_project/try_block_design/try_block_design.srcs/sources_1/bd/design_1/ip/design_1_FSRCNN_0_8/constraints/FSRCNN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FSRCNN_0_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/UIUC_GRAD/UIUC_ECE527/Final_project/try_block_design/try_block_design.srcs/sources_1/bd/design_1/ip/design_1_FSRCNN_0_8/design_1_FSRCNN_0_8.xci
# IP: The module: 'design_1_FSRCNN_0_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UIUC_GRAD/UIUC_ECE527/Final_project/try_block_design/try_block_design.srcs/sources_1/bd/design_1/ip/design_1_FSRCNN_0_8/constraints/FSRCNN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FSRCNN_0_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
