// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _CORRELATE_2_HH_
#define _CORRELATE_2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "FSRCNN_mul_mul_7sbkb.h"

namespace ap_rtl {

struct CORRELATE_2 : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<13> > prev_output_channel_V_address0;
    sc_out< sc_logic > prev_output_channel_V_ce0;
    sc_in< sc_lv<12> > prev_output_channel_V_q0;
    sc_out< sc_lv<5> > filter_V_address0;
    sc_out< sc_logic > filter_V_ce0;
    sc_in< sc_lv<7> > filter_V_q0;
    sc_out< sc_lv<6> > correlate_img_V_address0;
    sc_out< sc_logic > correlate_img_V_ce0;
    sc_out< sc_logic > correlate_img_V_we0;
    sc_out< sc_lv<12> > correlate_img_V_d0;


    // Module declarations
    CORRELATE_2(sc_module_name name);
    SC_HAS_PROCESS(CORRELATE_2);

    ~CORRELATE_2();

    sc_trace_file* mVcdFile;

    FSRCNN_mul_mul_7sbkb<1,1,7,12,19>* FSRCNN_mul_mul_7sbkb_U1;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<11> > index_fu_177_p2;
    sc_signal< sc_lv<11> > index_reg_489;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<23> > add_ln49_fu_183_p2;
    sc_signal< sc_lv<23> > add_ln49_reg_494;
    sc_signal< sc_lv<1> > icmp_ln46_fu_171_p2;
    sc_signal< sc_lv<7> > tmp_fu_189_p4;
    sc_signal< sc_lv<7> > tmp_reg_499;
    sc_signal< sc_lv<7> > k_y_fu_225_p2;
    sc_signal< sc_lv<7> > k_y_reg_504;
    sc_signal< sc_lv<1> > tmp_87_fu_231_p3;
    sc_signal< sc_lv<1> > tmp_87_reg_509;
    sc_signal< sc_lv<1> > icmp_ln55_fu_239_p2;
    sc_signal< sc_lv<1> > icmp_ln55_reg_513;
    sc_signal< sc_lv<1> > icmp_ln55_1_fu_245_p2;
    sc_signal< sc_lv<1> > icmp_ln55_1_reg_519;
    sc_signal< sc_lv<4> > tmp_88_reg_525;
    sc_signal< sc_lv<1> > and_ln65_fu_279_p2;
    sc_signal< sc_lv<1> > and_ln65_reg_531;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > select_ln55_1_fu_337_p3;
    sc_signal< sc_lv<32> > select_ln55_1_reg_540;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<12> > prev_output_channel_1_reg_545;
    sc_signal< sc_lv<19> > r_V_fu_468_p2;
    sc_signal< sc_lv<19> > r_V_reg_555;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<11> > select_ln71_fu_440_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<11> > select_ln71_1_fu_460_p3;
    sc_signal< sc_lv<11> > index_0_reg_125;
    sc_signal< sc_lv<23> > phi_mul_reg_136;
    sc_signal< sc_lv<11> > phi_urem_reg_147;
    sc_signal< sc_lv<11> > phi_urem33_reg_159;
    sc_signal< sc_lv<64> > zext_ln1116_5_fu_322_p1;
    sc_signal< sc_lv<64> > sext_ln62_fu_344_p1;
    sc_signal< sc_lv<64> > zext_ln68_fu_414_p1;
    sc_signal< sc_lv<32> > index_filter_1_fu_78;
    sc_signal< sc_lv<32> > index_filter_fu_409_p2;
    sc_signal< sc_lv<12> > sum_V_1_fu_82;
    sc_signal< sc_lv<5> > trunc_ln50_1_fu_203_p1;
    sc_signal< sc_lv<5> > mul_ln50_fu_211_p1;
    sc_signal< sc_lv<7> > trunc_ln51_1_fu_221_p1;
    sc_signal< sc_lv<3> > trunc_ln51_fu_217_p1;
    sc_signal< sc_lv<12> > mul_ln50_fu_211_p2;
    sc_signal< sc_lv<6> > trunc_ln50_fu_199_p1;
    sc_signal< sc_lv<6> > add_ln65_fu_261_p2;
    sc_signal< sc_lv<1> > icmp_ln65_fu_267_p2;
    sc_signal< sc_lv<1> > icmp_ln65_1_fu_273_p2;
    sc_signal< sc_lv<10> > tmp_89_fu_288_p3;
    sc_signal< sc_lv<6> > tmp_90_fu_299_p3;
    sc_signal< sc_lv<12> > zext_ln1116_3_fu_295_p1;
    sc_signal< sc_lv<12> > zext_ln1116_4_fu_306_p1;
    sc_signal< sc_lv<12> > zext_ln1116_fu_285_p1;
    sc_signal< sc_lv<12> > add_ln1116_fu_310_p2;
    sc_signal< sc_lv<12> > add_ln1116_2_fu_316_p2;
    sc_signal< sc_lv<32> > select_ln55_fu_330_p3;
    sc_signal< sc_lv<12> > select_ln55_2_fu_362_p3;
    sc_signal< sc_lv<12> > select_ln55_3_fu_369_p3;
    sc_signal< sc_lv<16> > lhs_V_fu_376_p3;
    sc_signal< sc_lv<24> > sext_ln1118_4_fu_359_p1;
    sc_signal< sc_lv<25> > zext_ln703_fu_388_p1;
    sc_signal< sc_lv<25> > zext_ln728_fu_384_p1;
    sc_signal< sc_lv<25> > ret_V_fu_392_p2;
    sc_signal< sc_lv<11> > add_ln71_fu_428_p2;
    sc_signal< sc_lv<1> > icmp_ln71_fu_434_p2;
    sc_signal< sc_lv<11> > add_ln71_1_fu_448_p2;
    sc_signal< sc_lv<1> > icmp_ln71_1_fu_454_p2;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< sc_lv<12> > mul_ln50_fu_211_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<11> ap_const_lv11_640;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<23> ap_const_lv23_A3E;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<12> ap_const_lv12_34;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<5> ap_const_lv5_5;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<6> ap_const_lv6_2C;
    static const sc_lv<6> ap_const_lv6_5;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<11> ap_const_lv11_5;
    static const sc_lv<11> ap_const_lv11_19;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln1116_2_fu_316_p2();
    void thread_add_ln1116_fu_310_p2();
    void thread_add_ln49_fu_183_p2();
    void thread_add_ln65_fu_261_p2();
    void thread_add_ln71_1_fu_448_p2();
    void thread_add_ln71_fu_428_p2();
    void thread_and_ln65_fu_279_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_correlate_img_V_address0();
    void thread_correlate_img_V_ce0();
    void thread_correlate_img_V_d0();
    void thread_correlate_img_V_we0();
    void thread_filter_V_address0();
    void thread_filter_V_ce0();
    void thread_icmp_ln46_fu_171_p2();
    void thread_icmp_ln55_1_fu_245_p2();
    void thread_icmp_ln55_fu_239_p2();
    void thread_icmp_ln65_1_fu_273_p2();
    void thread_icmp_ln65_fu_267_p2();
    void thread_icmp_ln71_1_fu_454_p2();
    void thread_icmp_ln71_fu_434_p2();
    void thread_index_filter_fu_409_p2();
    void thread_index_fu_177_p2();
    void thread_k_y_fu_225_p2();
    void thread_lhs_V_fu_376_p3();
    void thread_mul_ln50_fu_211_p1();
    void thread_mul_ln50_fu_211_p10();
    void thread_mul_ln50_fu_211_p2();
    void thread_prev_output_channel_V_address0();
    void thread_prev_output_channel_V_ce0();
    void thread_ret_V_fu_392_p2();
    void thread_select_ln55_1_fu_337_p3();
    void thread_select_ln55_2_fu_362_p3();
    void thread_select_ln55_3_fu_369_p3();
    void thread_select_ln55_fu_330_p3();
    void thread_select_ln71_1_fu_460_p3();
    void thread_select_ln71_fu_440_p3();
    void thread_sext_ln1118_4_fu_359_p1();
    void thread_sext_ln62_fu_344_p1();
    void thread_tmp_87_fu_231_p3();
    void thread_tmp_89_fu_288_p3();
    void thread_tmp_90_fu_299_p3();
    void thread_tmp_fu_189_p4();
    void thread_trunc_ln50_1_fu_203_p1();
    void thread_trunc_ln50_fu_199_p1();
    void thread_trunc_ln51_1_fu_221_p1();
    void thread_trunc_ln51_fu_217_p1();
    void thread_zext_ln1116_3_fu_295_p1();
    void thread_zext_ln1116_4_fu_306_p1();
    void thread_zext_ln1116_5_fu_322_p1();
    void thread_zext_ln1116_fu_285_p1();
    void thread_zext_ln68_fu_414_p1();
    void thread_zext_ln703_fu_388_p1();
    void thread_zext_ln728_fu_384_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
