// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _CORRELATE_1_HH_
#define _CORRELATE_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "FSRCNN_mul_mul_12CeG.h"

namespace ap_rtl {

struct CORRELATE_1 : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<13> > prev_output_channel_V_address0;
    sc_out< sc_logic > prev_output_channel_V_ce0;
    sc_in< sc_lv<12> > prev_output_channel_V_q0;
    sc_out< sc_lv<4> > filter_V_address0;
    sc_out< sc_logic > filter_V_ce0;
    sc_in< sc_lv<12> > filter_V_q0;
    sc_out< sc_lv<6> > correlate_img_V_address0;
    sc_out< sc_logic > correlate_img_V_ce0;
    sc_out< sc_logic > correlate_img_V_we0;
    sc_out< sc_lv<12> > correlate_img_V_d0;


    // Module declarations
    CORRELATE_1(sc_module_name name);
    SC_HAS_PROCESS(CORRELATE_1);

    ~CORRELATE_1();

    sc_trace_file* mVcdFile;

    FSRCNN_mul_mul_12CeG<1,1,12,12,24>* FSRCNN_mul_mul_12CeG_U56;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<10> > index_fu_171_p2;
    sc_signal< sc_lv<10> > index_reg_475;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<21> > add_ln49_fu_177_p2;
    sc_signal< sc_lv<21> > add_ln49_reg_480;
    sc_signal< sc_lv<1> > icmp_ln46_fu_165_p2;
    sc_signal< sc_lv<7> > tmp_91_fu_183_p4;
    sc_signal< sc_lv<7> > tmp_91_reg_485;
    sc_signal< sc_lv<7> > k_y_fu_215_p2;
    sc_signal< sc_lv<7> > k_y_reg_490;
    sc_signal< sc_lv<1> > tmp_92_fu_221_p3;
    sc_signal< sc_lv<1> > tmp_92_reg_495;
    sc_signal< sc_lv<1> > icmp_ln55_fu_229_p2;
    sc_signal< sc_lv<1> > icmp_ln55_reg_499;
    sc_signal< sc_lv<1> > icmp_ln55_1_fu_235_p2;
    sc_signal< sc_lv<1> > icmp_ln55_1_reg_505;
    sc_signal< sc_lv<4> > tmp_reg_511;
    sc_signal< sc_lv<1> > and_ln65_fu_269_p2;
    sc_signal< sc_lv<1> > and_ln65_reg_517;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > select_ln55_fu_327_p3;
    sc_signal< sc_lv<32> > select_ln55_reg_526;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<12> > prev_output_channel_2_reg_531;
    sc_signal< sc_lv<24> > r_V_6_fu_454_p2;
    sc_signal< sc_lv<24> > r_V_6_reg_541;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<10> > select_ln71_fu_426_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<10> > select_ln71_2_fu_446_p3;
    sc_signal< sc_lv<10> > index_0_reg_119;
    sc_signal< sc_lv<21> > phi_mul_reg_130;
    sc_signal< sc_lv<10> > phi_urem_reg_141;
    sc_signal< sc_lv<10> > phi_urem33_reg_153;
    sc_signal< sc_lv<64> > zext_ln1116_8_fu_312_p1;
    sc_signal< sc_lv<64> > sext_ln62_fu_334_p1;
    sc_signal< sc_lv<64> > zext_ln68_fu_400_p1;
    sc_signal< sc_lv<32> > index_filter_2_fu_72;
    sc_signal< sc_lv<32> > index_filter_fu_395_p2;
    sc_signal< sc_lv<12> > sum_V_2_fu_76;
    sc_signal< sc_lv<4> > trunc_ln50_fu_193_p1;
    sc_signal< sc_lv<4> > mul_ln50_fu_201_p1;
    sc_signal< sc_lv<7> > trunc_ln51_2_fu_211_p1;
    sc_signal< sc_lv<2> > trunc_ln51_fu_207_p1;
    sc_signal< sc_lv<10> > mul_ln50_fu_201_p2;
    sc_signal< sc_lv<4> > add_ln65_fu_251_p2;
    sc_signal< sc_lv<1> > icmp_ln65_fu_257_p2;
    sc_signal< sc_lv<1> > icmp_ln65_1_fu_263_p2;
    sc_signal< sc_lv<10> > tmp_s_fu_278_p3;
    sc_signal< sc_lv<6> > tmp_128_fu_289_p3;
    sc_signal< sc_lv<11> > zext_ln1116_7_fu_296_p1;
    sc_signal< sc_lv<11> > zext_ln1116_6_fu_285_p1;
    sc_signal< sc_lv<11> > add_ln1116_fu_300_p2;
    sc_signal< sc_lv<11> > zext_ln1116_fu_275_p1;
    sc_signal< sc_lv<11> > add_ln1116_3_fu_306_p2;
    sc_signal< sc_lv<32> > select_ln55_1_fu_320_p3;
    sc_signal< sc_lv<12> > select_ln55_4_fu_349_p3;
    sc_signal< sc_lv<12> > select_ln55_5_fu_356_p3;
    sc_signal< sc_lv<16> > lhs_V_fu_363_p3;
    sc_signal< sc_lv<25> > zext_ln728_fu_371_p1;
    sc_signal< sc_lv<25> > zext_ln703_fu_375_p1;
    sc_signal< sc_lv<25> > ret_V_fu_378_p2;
    sc_signal< sc_lv<10> > add_ln71_fu_414_p2;
    sc_signal< sc_lv<1> > icmp_ln71_fu_420_p2;
    sc_signal< sc_lv<10> > add_ln71_2_fu_434_p2;
    sc_signal< sc_lv<1> > icmp_ln71_2_fu_440_p2;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< sc_lv<10> > mul_ln50_fu_201_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<21> ap_const_lv21_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<10> ap_const_lv10_240;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<21> ap_const_lv21_71D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<10> ap_const_lv10_16;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<10> ap_const_lv10_3;
    static const sc_lv<10> ap_const_lv10_9;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln1116_3_fu_306_p2();
    void thread_add_ln1116_fu_300_p2();
    void thread_add_ln49_fu_177_p2();
    void thread_add_ln65_fu_251_p2();
    void thread_add_ln71_2_fu_434_p2();
    void thread_add_ln71_fu_414_p2();
    void thread_and_ln65_fu_269_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_correlate_img_V_address0();
    void thread_correlate_img_V_ce0();
    void thread_correlate_img_V_d0();
    void thread_correlate_img_V_we0();
    void thread_filter_V_address0();
    void thread_filter_V_ce0();
    void thread_icmp_ln46_fu_165_p2();
    void thread_icmp_ln55_1_fu_235_p2();
    void thread_icmp_ln55_fu_229_p2();
    void thread_icmp_ln65_1_fu_263_p2();
    void thread_icmp_ln65_fu_257_p2();
    void thread_icmp_ln71_2_fu_440_p2();
    void thread_icmp_ln71_fu_420_p2();
    void thread_index_filter_fu_395_p2();
    void thread_index_fu_171_p2();
    void thread_k_y_fu_215_p2();
    void thread_lhs_V_fu_363_p3();
    void thread_mul_ln50_fu_201_p1();
    void thread_mul_ln50_fu_201_p10();
    void thread_mul_ln50_fu_201_p2();
    void thread_prev_output_channel_V_address0();
    void thread_prev_output_channel_V_ce0();
    void thread_ret_V_fu_378_p2();
    void thread_select_ln55_1_fu_320_p3();
    void thread_select_ln55_4_fu_349_p3();
    void thread_select_ln55_5_fu_356_p3();
    void thread_select_ln55_fu_327_p3();
    void thread_select_ln71_2_fu_446_p3();
    void thread_select_ln71_fu_426_p3();
    void thread_sext_ln62_fu_334_p1();
    void thread_tmp_128_fu_289_p3();
    void thread_tmp_91_fu_183_p4();
    void thread_tmp_92_fu_221_p3();
    void thread_tmp_s_fu_278_p3();
    void thread_trunc_ln50_fu_193_p1();
    void thread_trunc_ln51_2_fu_211_p1();
    void thread_trunc_ln51_fu_207_p1();
    void thread_zext_ln1116_6_fu_285_p1();
    void thread_zext_ln1116_7_fu_296_p1();
    void thread_zext_ln1116_8_fu_312_p1();
    void thread_zext_ln1116_fu_275_p1();
    void thread_zext_ln68_fu_400_p1();
    void thread_zext_ln703_fu_375_p1();
    void thread_zext_ln728_fu_371_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
