// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FSRCNN,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.634000,HLS_SYN_LAT=169804607,HLS_SYN_TPT=169803548,HLS_SYN_MEM=161,HLS_SYN_DSP=11,HLS_SYN_FF=12956,HLS_SYN_LUT=38739,HLS_VERSION=2019_1}" *)

module FSRCNN (
        s_axi_scalar_parameters_AWVALID,
        s_axi_scalar_parameters_AWREADY,
        s_axi_scalar_parameters_AWADDR,
        s_axi_scalar_parameters_WVALID,
        s_axi_scalar_parameters_WREADY,
        s_axi_scalar_parameters_WDATA,
        s_axi_scalar_parameters_WSTRB,
        s_axi_scalar_parameters_ARVALID,
        s_axi_scalar_parameters_ARREADY,
        s_axi_scalar_parameters_ARADDR,
        s_axi_scalar_parameters_RVALID,
        s_axi_scalar_parameters_RREADY,
        s_axi_scalar_parameters_RDATA,
        s_axi_scalar_parameters_RRESP,
        s_axi_scalar_parameters_BVALID,
        s_axi_scalar_parameters_BREADY,
        s_axi_scalar_parameters_BRESP,
        ap_clk,
        ap_rst_n,
        stream_in_TDATA,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TUSER,
        stream_in_TLAST,
        stream_in_TID,
        stream_in_TDEST,
        stream_out_TDATA,
        stream_out_TKEEP,
        stream_out_TSTRB,
        stream_out_TUSER,
        stream_out_TLAST,
        stream_out_TID,
        stream_out_TDEST,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_out_TVALID,
        stream_out_TREADY
);

parameter    C_S_AXI_SCALAR_PARAMETERS_DATA_WIDTH = 32;
parameter    C_S_AXI_SCALAR_PARAMETERS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_SCALAR_PARAMETERS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_scalar_parameters_AWVALID;
output   s_axi_scalar_parameters_AWREADY;
input  [C_S_AXI_SCALAR_PARAMETERS_ADDR_WIDTH - 1:0] s_axi_scalar_parameters_AWADDR;
input   s_axi_scalar_parameters_WVALID;
output   s_axi_scalar_parameters_WREADY;
input  [C_S_AXI_SCALAR_PARAMETERS_DATA_WIDTH - 1:0] s_axi_scalar_parameters_WDATA;
input  [C_S_AXI_SCALAR_PARAMETERS_WSTRB_WIDTH - 1:0] s_axi_scalar_parameters_WSTRB;
input   s_axi_scalar_parameters_ARVALID;
output   s_axi_scalar_parameters_ARREADY;
input  [C_S_AXI_SCALAR_PARAMETERS_ADDR_WIDTH - 1:0] s_axi_scalar_parameters_ARADDR;
output   s_axi_scalar_parameters_RVALID;
input   s_axi_scalar_parameters_RREADY;
output  [C_S_AXI_SCALAR_PARAMETERS_DATA_WIDTH - 1:0] s_axi_scalar_parameters_RDATA;
output  [1:0] s_axi_scalar_parameters_RRESP;
output   s_axi_scalar_parameters_BVALID;
input   s_axi_scalar_parameters_BREADY;
output  [1:0] s_axi_scalar_parameters_BRESP;
input   ap_clk;
input   ap_rst_n;
input  [31:0] stream_in_TDATA;
input  [3:0] stream_in_TKEEP;
input  [3:0] stream_in_TSTRB;
input  [0:0] stream_in_TUSER;
input  [0:0] stream_in_TLAST;
input  [0:0] stream_in_TID;
input  [0:0] stream_in_TDEST;
output  [31:0] stream_out_TDATA;
output  [3:0] stream_out_TKEEP;
output  [3:0] stream_out_TSTRB;
output  [0:0] stream_out_TUSER;
output  [0:0] stream_out_TLAST;
output  [0:0] stream_out_TID;
output  [0:0] stream_out_TDEST;
input   stream_in_TVALID;
output   stream_in_TREADY;
output   stream_out_TVALID;
input   stream_out_TREADY;

 reg    ap_rst_n_inv;
wire   [7:0] height_V;
wire   [7:0] width_V;
wire   [7:0] scale_factor_V;
wire    conrr_layer1_U0_ap_start;
wire    conrr_layer1_U0_ap_done;
wire    conrr_layer1_U0_ap_continue;
wire    conrr_layer1_U0_ap_idle;
wire    conrr_layer1_U0_ap_ready;
wire    conrr_layer1_U0_start_out;
wire    conrr_layer1_U0_start_write;
wire    conrr_layer1_U0_stream_in_TREADY;
wire   [0:0] conrr_layer1_U0_corr1_out_V_valid_V_din;
wire    conrr_layer1_U0_corr1_out_V_valid_V_write;
wire   [11:0] conrr_layer1_U0_corr1_out_V_data_V_din;
wire    conrr_layer1_U0_corr1_out_V_data_V_write;
wire   [3:0] conrr_layer1_U0_corr1_out_V_keep_V_din;
wire    conrr_layer1_U0_corr1_out_V_keep_V_write;
wire   [0:0] conrr_layer1_U0_corr1_out_V_user_V_din;
wire    conrr_layer1_U0_corr1_out_V_user_V_write;
wire   [0:0] conrr_layer1_U0_corr1_out_V_last_V_din;
wire    conrr_layer1_U0_corr1_out_V_last_V_write;
wire   [0:0] conrr_layer1_U0_corr1_out_V_id_V_din;
wire    conrr_layer1_U0_corr1_out_V_id_V_write;
wire   [0:0] conrr_layer1_U0_corr1_out_V_dest_V_din;
wire    conrr_layer1_U0_corr1_out_V_dest_V_write;
wire    conrr_layer2_U0_ap_start;
wire    conrr_layer2_U0_ap_done;
wire    conrr_layer2_U0_ap_continue;
wire    conrr_layer2_U0_ap_idle;
wire    conrr_layer2_U0_ap_ready;
wire    conrr_layer2_U0_start_out;
wire    conrr_layer2_U0_start_write;
wire    conrr_layer2_U0_corr1_out_V_valid_V_read;
wire    conrr_layer2_U0_corr1_out_V_data_V_read;
wire    conrr_layer2_U0_corr1_out_V_keep_V_read;
wire    conrr_layer2_U0_corr1_out_V_user_V_read;
wire    conrr_layer2_U0_corr1_out_V_last_V_read;
wire    conrr_layer2_U0_corr1_out_V_id_V_read;
wire    conrr_layer2_U0_corr1_out_V_dest_V_read;
wire   [0:0] conrr_layer2_U0_corr2_out_V_valid_V_din;
wire    conrr_layer2_U0_corr2_out_V_valid_V_write;
wire   [11:0] conrr_layer2_U0_corr2_out_V_data_V_din;
wire    conrr_layer2_U0_corr2_out_V_data_V_write;
wire   [3:0] conrr_layer2_U0_corr2_out_V_keep_V_din;
wire    conrr_layer2_U0_corr2_out_V_keep_V_write;
wire   [0:0] conrr_layer2_U0_corr2_out_V_user_V_din;
wire    conrr_layer2_U0_corr2_out_V_user_V_write;
wire   [0:0] conrr_layer2_U0_corr2_out_V_last_V_din;
wire    conrr_layer2_U0_corr2_out_V_last_V_write;
wire   [0:0] conrr_layer2_U0_corr2_out_V_id_V_din;
wire    conrr_layer2_U0_corr2_out_V_id_V_write;
wire   [0:0] conrr_layer2_U0_corr2_out_V_dest_V_din;
wire    conrr_layer2_U0_corr2_out_V_dest_V_write;
wire    conrr_layer3_U0_ap_start;
wire    conrr_layer3_U0_ap_done;
wire    conrr_layer3_U0_ap_continue;
wire    conrr_layer3_U0_ap_idle;
wire    conrr_layer3_U0_ap_ready;
wire    conrr_layer3_U0_start_out;
wire    conrr_layer3_U0_start_write;
wire    conrr_layer3_U0_corr2_out_V_valid_V_read;
wire    conrr_layer3_U0_corr2_out_V_data_V_read;
wire    conrr_layer3_U0_corr2_out_V_keep_V_read;
wire    conrr_layer3_U0_corr2_out_V_user_V_read;
wire    conrr_layer3_U0_corr2_out_V_last_V_read;
wire    conrr_layer3_U0_corr2_out_V_id_V_read;
wire    conrr_layer3_U0_corr2_out_V_dest_V_read;
wire   [0:0] conrr_layer3_U0_corr3_out_V_valid_V_din;
wire    conrr_layer3_U0_corr3_out_V_valid_V_write;
wire   [11:0] conrr_layer3_U0_corr3_out_V_data_V_din;
wire    conrr_layer3_U0_corr3_out_V_data_V_write;
wire   [3:0] conrr_layer3_U0_corr3_out_V_keep_V_din;
wire    conrr_layer3_U0_corr3_out_V_keep_V_write;
wire   [0:0] conrr_layer3_U0_corr3_out_V_user_V_din;
wire    conrr_layer3_U0_corr3_out_V_user_V_write;
wire   [0:0] conrr_layer3_U0_corr3_out_V_last_V_din;
wire    conrr_layer3_U0_corr3_out_V_last_V_write;
wire   [0:0] conrr_layer3_U0_corr3_out_V_id_V_din;
wire    conrr_layer3_U0_corr3_out_V_id_V_write;
wire   [0:0] conrr_layer3_U0_corr3_out_V_dest_V_din;
wire    conrr_layer3_U0_corr3_out_V_dest_V_write;
wire    conrr_layer4_U0_ap_start;
wire    conrr_layer4_U0_ap_done;
wire    conrr_layer4_U0_ap_continue;
wire    conrr_layer4_U0_ap_idle;
wire    conrr_layer4_U0_ap_ready;
wire    conrr_layer4_U0_start_out;
wire    conrr_layer4_U0_start_write;
wire    conrr_layer4_U0_corr3_out_V_valid_V_read;
wire    conrr_layer4_U0_corr3_out_V_data_V_read;
wire    conrr_layer4_U0_corr3_out_V_keep_V_read;
wire    conrr_layer4_U0_corr3_out_V_user_V_read;
wire    conrr_layer4_U0_corr3_out_V_last_V_read;
wire    conrr_layer4_U0_corr3_out_V_id_V_read;
wire    conrr_layer4_U0_corr3_out_V_dest_V_read;
wire   [0:0] conrr_layer4_U0_corr4_out_V_valid_V_din;
wire    conrr_layer4_U0_corr4_out_V_valid_V_write;
wire   [11:0] conrr_layer4_U0_corr4_out_V_data_V_din;
wire    conrr_layer4_U0_corr4_out_V_data_V_write;
wire   [3:0] conrr_layer4_U0_corr4_out_V_keep_V_din;
wire    conrr_layer4_U0_corr4_out_V_keep_V_write;
wire   [0:0] conrr_layer4_U0_corr4_out_V_user_V_din;
wire    conrr_layer4_U0_corr4_out_V_user_V_write;
wire   [0:0] conrr_layer4_U0_corr4_out_V_last_V_din;
wire    conrr_layer4_U0_corr4_out_V_last_V_write;
wire   [0:0] conrr_layer4_U0_corr4_out_V_id_V_din;
wire    conrr_layer4_U0_corr4_out_V_id_V_write;
wire   [0:0] conrr_layer4_U0_corr4_out_V_dest_V_din;
wire    conrr_layer4_U0_corr4_out_V_dest_V_write;
wire    conrr_layer5_U0_ap_start;
wire    conrr_layer5_U0_ap_done;
wire    conrr_layer5_U0_ap_continue;
wire    conrr_layer5_U0_ap_idle;
wire    conrr_layer5_U0_ap_ready;
wire    conrr_layer5_U0_start_out;
wire    conrr_layer5_U0_start_write;
wire    conrr_layer5_U0_corr4_out_V_valid_V_read;
wire    conrr_layer5_U0_corr4_out_V_data_V_read;
wire    conrr_layer5_U0_corr4_out_V_keep_V_read;
wire    conrr_layer5_U0_corr4_out_V_user_V_read;
wire    conrr_layer5_U0_corr4_out_V_last_V_read;
wire    conrr_layer5_U0_corr4_out_V_id_V_read;
wire    conrr_layer5_U0_corr4_out_V_dest_V_read;
wire   [0:0] conrr_layer5_U0_corr5_out_V_valid_V_din;
wire    conrr_layer5_U0_corr5_out_V_valid_V_write;
wire   [11:0] conrr_layer5_U0_corr5_out_V_data_V_din;
wire    conrr_layer5_U0_corr5_out_V_data_V_write;
wire   [3:0] conrr_layer5_U0_corr5_out_V_keep_V_din;
wire    conrr_layer5_U0_corr5_out_V_keep_V_write;
wire   [0:0] conrr_layer5_U0_corr5_out_V_user_V_din;
wire    conrr_layer5_U0_corr5_out_V_user_V_write;
wire   [0:0] conrr_layer5_U0_corr5_out_V_last_V_din;
wire    conrr_layer5_U0_corr5_out_V_last_V_write;
wire   [0:0] conrr_layer5_U0_corr5_out_V_id_V_din;
wire    conrr_layer5_U0_corr5_out_V_id_V_write;
wire   [0:0] conrr_layer5_U0_corr5_out_V_dest_V_din;
wire    conrr_layer5_U0_corr5_out_V_dest_V_write;
wire    conrr_layer6_U0_ap_start;
wire    conrr_layer6_U0_ap_done;
wire    conrr_layer6_U0_ap_continue;
wire    conrr_layer6_U0_ap_idle;
wire    conrr_layer6_U0_ap_ready;
wire    conrr_layer6_U0_start_out;
wire    conrr_layer6_U0_start_write;
wire    conrr_layer6_U0_corr5_out_V_valid_V_read;
wire    conrr_layer6_U0_corr5_out_V_data_V_read;
wire    conrr_layer6_U0_corr5_out_V_keep_V_read;
wire    conrr_layer6_U0_corr5_out_V_user_V_read;
wire    conrr_layer6_U0_corr5_out_V_last_V_read;
wire    conrr_layer6_U0_corr5_out_V_id_V_read;
wire    conrr_layer6_U0_corr5_out_V_dest_V_read;
wire   [0:0] conrr_layer6_U0_corr6_out_V_valid_V_din;
wire    conrr_layer6_U0_corr6_out_V_valid_V_write;
wire   [11:0] conrr_layer6_U0_corr6_out_V_data_V_din;
wire    conrr_layer6_U0_corr6_out_V_data_V_write;
wire   [3:0] conrr_layer6_U0_corr6_out_V_keep_V_din;
wire    conrr_layer6_U0_corr6_out_V_keep_V_write;
wire   [0:0] conrr_layer6_U0_corr6_out_V_user_V_din;
wire    conrr_layer6_U0_corr6_out_V_user_V_write;
wire   [0:0] conrr_layer6_U0_corr6_out_V_last_V_din;
wire    conrr_layer6_U0_corr6_out_V_last_V_write;
wire   [0:0] conrr_layer6_U0_corr6_out_V_id_V_din;
wire    conrr_layer6_U0_corr6_out_V_id_V_write;
wire   [0:0] conrr_layer6_U0_corr6_out_V_dest_V_din;
wire    conrr_layer6_U0_corr6_out_V_dest_V_write;
wire    conrr_layer7_U0_ap_start;
wire    conrr_layer7_U0_ap_done;
wire    conrr_layer7_U0_ap_continue;
wire    conrr_layer7_U0_ap_idle;
wire    conrr_layer7_U0_ap_ready;
wire    conrr_layer7_U0_start_out;
wire    conrr_layer7_U0_start_write;
wire    conrr_layer7_U0_corr6_out_V_valid_V_read;
wire    conrr_layer7_U0_corr6_out_V_data_V_read;
wire    conrr_layer7_U0_corr6_out_V_keep_V_read;
wire    conrr_layer7_U0_corr6_out_V_user_V_read;
wire    conrr_layer7_U0_corr6_out_V_last_V_read;
wire    conrr_layer7_U0_corr6_out_V_id_V_read;
wire    conrr_layer7_U0_corr6_out_V_dest_V_read;
wire   [0:0] conrr_layer7_U0_corr7_out_V_valid_V_din;
wire    conrr_layer7_U0_corr7_out_V_valid_V_write;
wire   [11:0] conrr_layer7_U0_corr7_out_V_data_V_din;
wire    conrr_layer7_U0_corr7_out_V_data_V_write;
wire   [3:0] conrr_layer7_U0_corr7_out_V_keep_V_din;
wire    conrr_layer7_U0_corr7_out_V_keep_V_write;
wire   [0:0] conrr_layer7_U0_corr7_out_V_user_V_din;
wire    conrr_layer7_U0_corr7_out_V_user_V_write;
wire   [0:0] conrr_layer7_U0_corr7_out_V_last_V_din;
wire    conrr_layer7_U0_corr7_out_V_last_V_write;
wire   [0:0] conrr_layer7_U0_corr7_out_V_id_V_din;
wire    conrr_layer7_U0_corr7_out_V_id_V_write;
wire   [0:0] conrr_layer7_U0_corr7_out_V_dest_V_din;
wire    conrr_layer7_U0_corr7_out_V_dest_V_write;
wire    decorr_layer8_U0_ap_start;
wire    decorr_layer8_U0_ap_done;
wire    decorr_layer8_U0_ap_continue;
wire    decorr_layer8_U0_ap_idle;
wire    decorr_layer8_U0_ap_ready;
wire    decorr_layer8_U0_start_out;
wire    decorr_layer8_U0_start_write;
wire    decorr_layer8_U0_corr7_out_V_valid_V_read;
wire    decorr_layer8_U0_corr7_out_V_data_V_read;
wire    decorr_layer8_U0_corr7_out_V_keep_V_read;
wire    decorr_layer8_U0_corr7_out_V_user_V_read;
wire    decorr_layer8_U0_corr7_out_V_last_V_read;
wire    decorr_layer8_U0_corr7_out_V_id_V_read;
wire    decorr_layer8_U0_corr7_out_V_dest_V_read;
wire   [0:0] decorr_layer8_U0_corr8_out_V_valid_V_din;
wire    decorr_layer8_U0_corr8_out_V_valid_V_write;
wire   [11:0] decorr_layer8_U0_corr8_out_V_data_V_din;
wire    decorr_layer8_U0_corr8_out_V_data_V_write;
wire   [3:0] decorr_layer8_U0_corr8_out_V_keep_V_din;
wire    decorr_layer8_U0_corr8_out_V_keep_V_write;
wire   [0:0] decorr_layer8_U0_corr8_out_V_user_V_din;
wire    decorr_layer8_U0_corr8_out_V_user_V_write;
wire   [0:0] decorr_layer8_U0_corr8_out_V_last_V_din;
wire    decorr_layer8_U0_corr8_out_V_last_V_write;
wire   [0:0] decorr_layer8_U0_corr8_out_V_id_V_din;
wire    decorr_layer8_U0_corr8_out_V_id_V_write;
wire   [0:0] decorr_layer8_U0_corr8_out_V_dest_V_din;
wire    decorr_layer8_U0_corr8_out_V_dest_V_write;
wire    Loop_1_proc378_U0_ap_start;
wire    Loop_1_proc378_U0_ap_done;
wire    Loop_1_proc378_U0_ap_continue;
wire    Loop_1_proc378_U0_ap_idle;
wire    Loop_1_proc378_U0_ap_ready;
wire    Loop_1_proc378_U0_corr8_out_V_valid_V_read;
wire    Loop_1_proc378_U0_corr8_out_V_data_V_read;
wire    Loop_1_proc378_U0_corr8_out_V_keep_V_read;
wire    Loop_1_proc378_U0_corr8_out_V_user_V_read;
wire    Loop_1_proc378_U0_corr8_out_V_last_V_read;
wire    Loop_1_proc378_U0_corr8_out_V_id_V_read;
wire    Loop_1_proc378_U0_corr8_out_V_dest_V_read;
wire   [31:0] Loop_1_proc378_U0_stream_out_TDATA;
wire    Loop_1_proc378_U0_stream_out_TVALID;
wire   [3:0] Loop_1_proc378_U0_stream_out_TKEEP;
wire   [3:0] Loop_1_proc378_U0_stream_out_TSTRB;
wire   [0:0] Loop_1_proc378_U0_stream_out_TUSER;
wire   [0:0] Loop_1_proc378_U0_stream_out_TLAST;
wire   [0:0] Loop_1_proc378_U0_stream_out_TID;
wire   [0:0] Loop_1_proc378_U0_stream_out_TDEST;
wire    ap_sync_continue;
wire    corr1_out_V_valid_V_full_n;
wire   [0:0] corr1_out_V_valid_V_dout;
wire    corr1_out_V_valid_V_empty_n;
wire    corr1_out_V_data_V_full_n;
wire   [11:0] corr1_out_V_data_V_dout;
wire    corr1_out_V_data_V_empty_n;
wire    corr1_out_V_keep_V_full_n;
wire   [3:0] corr1_out_V_keep_V_dout;
wire    corr1_out_V_keep_V_empty_n;
wire    corr1_out_V_user_V_full_n;
wire   [0:0] corr1_out_V_user_V_dout;
wire    corr1_out_V_user_V_empty_n;
wire    corr1_out_V_last_V_full_n;
wire   [0:0] corr1_out_V_last_V_dout;
wire    corr1_out_V_last_V_empty_n;
wire    corr1_out_V_id_V_full_n;
wire   [0:0] corr1_out_V_id_V_dout;
wire    corr1_out_V_id_V_empty_n;
wire    corr1_out_V_dest_V_full_n;
wire   [0:0] corr1_out_V_dest_V_dout;
wire    corr1_out_V_dest_V_empty_n;
wire    corr2_out_V_valid_V_full_n;
wire   [0:0] corr2_out_V_valid_V_dout;
wire    corr2_out_V_valid_V_empty_n;
wire    corr2_out_V_data_V_full_n;
wire   [11:0] corr2_out_V_data_V_dout;
wire    corr2_out_V_data_V_empty_n;
wire    corr2_out_V_keep_V_full_n;
wire   [3:0] corr2_out_V_keep_V_dout;
wire    corr2_out_V_keep_V_empty_n;
wire    corr2_out_V_user_V_full_n;
wire   [0:0] corr2_out_V_user_V_dout;
wire    corr2_out_V_user_V_empty_n;
wire    corr2_out_V_last_V_full_n;
wire   [0:0] corr2_out_V_last_V_dout;
wire    corr2_out_V_last_V_empty_n;
wire    corr2_out_V_id_V_full_n;
wire   [0:0] corr2_out_V_id_V_dout;
wire    corr2_out_V_id_V_empty_n;
wire    corr2_out_V_dest_V_full_n;
wire   [0:0] corr2_out_V_dest_V_dout;
wire    corr2_out_V_dest_V_empty_n;
wire    corr3_out_V_valid_V_full_n;
wire   [0:0] corr3_out_V_valid_V_dout;
wire    corr3_out_V_valid_V_empty_n;
wire    corr3_out_V_data_V_full_n;
wire   [11:0] corr3_out_V_data_V_dout;
wire    corr3_out_V_data_V_empty_n;
wire    corr3_out_V_keep_V_full_n;
wire   [3:0] corr3_out_V_keep_V_dout;
wire    corr3_out_V_keep_V_empty_n;
wire    corr3_out_V_user_V_full_n;
wire   [0:0] corr3_out_V_user_V_dout;
wire    corr3_out_V_user_V_empty_n;
wire    corr3_out_V_last_V_full_n;
wire   [0:0] corr3_out_V_last_V_dout;
wire    corr3_out_V_last_V_empty_n;
wire    corr3_out_V_id_V_full_n;
wire   [0:0] corr3_out_V_id_V_dout;
wire    corr3_out_V_id_V_empty_n;
wire    corr3_out_V_dest_V_full_n;
wire   [0:0] corr3_out_V_dest_V_dout;
wire    corr3_out_V_dest_V_empty_n;
wire    corr4_out_V_valid_V_full_n;
wire   [0:0] corr4_out_V_valid_V_dout;
wire    corr4_out_V_valid_V_empty_n;
wire    corr4_out_V_data_V_full_n;
wire   [11:0] corr4_out_V_data_V_dout;
wire    corr4_out_V_data_V_empty_n;
wire    corr4_out_V_keep_V_full_n;
wire   [3:0] corr4_out_V_keep_V_dout;
wire    corr4_out_V_keep_V_empty_n;
wire    corr4_out_V_user_V_full_n;
wire   [0:0] corr4_out_V_user_V_dout;
wire    corr4_out_V_user_V_empty_n;
wire    corr4_out_V_last_V_full_n;
wire   [0:0] corr4_out_V_last_V_dout;
wire    corr4_out_V_last_V_empty_n;
wire    corr4_out_V_id_V_full_n;
wire   [0:0] corr4_out_V_id_V_dout;
wire    corr4_out_V_id_V_empty_n;
wire    corr4_out_V_dest_V_full_n;
wire   [0:0] corr4_out_V_dest_V_dout;
wire    corr4_out_V_dest_V_empty_n;
wire    corr5_out_V_valid_V_full_n;
wire   [0:0] corr5_out_V_valid_V_dout;
wire    corr5_out_V_valid_V_empty_n;
wire    corr5_out_V_data_V_full_n;
wire   [11:0] corr5_out_V_data_V_dout;
wire    corr5_out_V_data_V_empty_n;
wire    corr5_out_V_keep_V_full_n;
wire   [3:0] corr5_out_V_keep_V_dout;
wire    corr5_out_V_keep_V_empty_n;
wire    corr5_out_V_user_V_full_n;
wire   [0:0] corr5_out_V_user_V_dout;
wire    corr5_out_V_user_V_empty_n;
wire    corr5_out_V_last_V_full_n;
wire   [0:0] corr5_out_V_last_V_dout;
wire    corr5_out_V_last_V_empty_n;
wire    corr5_out_V_id_V_full_n;
wire   [0:0] corr5_out_V_id_V_dout;
wire    corr5_out_V_id_V_empty_n;
wire    corr5_out_V_dest_V_full_n;
wire   [0:0] corr5_out_V_dest_V_dout;
wire    corr5_out_V_dest_V_empty_n;
wire    corr6_out_V_valid_V_full_n;
wire   [0:0] corr6_out_V_valid_V_dout;
wire    corr6_out_V_valid_V_empty_n;
wire    corr6_out_V_data_V_full_n;
wire   [11:0] corr6_out_V_data_V_dout;
wire    corr6_out_V_data_V_empty_n;
wire    corr6_out_V_keep_V_full_n;
wire   [3:0] corr6_out_V_keep_V_dout;
wire    corr6_out_V_keep_V_empty_n;
wire    corr6_out_V_user_V_full_n;
wire   [0:0] corr6_out_V_user_V_dout;
wire    corr6_out_V_user_V_empty_n;
wire    corr6_out_V_last_V_full_n;
wire   [0:0] corr6_out_V_last_V_dout;
wire    corr6_out_V_last_V_empty_n;
wire    corr6_out_V_id_V_full_n;
wire   [0:0] corr6_out_V_id_V_dout;
wire    corr6_out_V_id_V_empty_n;
wire    corr6_out_V_dest_V_full_n;
wire   [0:0] corr6_out_V_dest_V_dout;
wire    corr6_out_V_dest_V_empty_n;
wire    corr7_out_V_valid_V_full_n;
wire   [0:0] corr7_out_V_valid_V_dout;
wire    corr7_out_V_valid_V_empty_n;
wire    corr7_out_V_data_V_full_n;
wire   [11:0] corr7_out_V_data_V_dout;
wire    corr7_out_V_data_V_empty_n;
wire    corr7_out_V_keep_V_full_n;
wire   [3:0] corr7_out_V_keep_V_dout;
wire    corr7_out_V_keep_V_empty_n;
wire    corr7_out_V_user_V_full_n;
wire   [0:0] corr7_out_V_user_V_dout;
wire    corr7_out_V_user_V_empty_n;
wire    corr7_out_V_last_V_full_n;
wire   [0:0] corr7_out_V_last_V_dout;
wire    corr7_out_V_last_V_empty_n;
wire    corr7_out_V_id_V_full_n;
wire   [0:0] corr7_out_V_id_V_dout;
wire    corr7_out_V_id_V_empty_n;
wire    corr7_out_V_dest_V_full_n;
wire   [0:0] corr7_out_V_dest_V_dout;
wire    corr7_out_V_dest_V_empty_n;
wire    corr8_out_V_valid_V_full_n;
wire   [0:0] corr8_out_V_valid_V_dout;
wire    corr8_out_V_valid_V_empty_n;
wire    corr8_out_V_data_V_full_n;
wire   [11:0] corr8_out_V_data_V_dout;
wire    corr8_out_V_data_V_empty_n;
wire    corr8_out_V_keep_V_full_n;
wire   [3:0] corr8_out_V_keep_V_dout;
wire    corr8_out_V_keep_V_empty_n;
wire    corr8_out_V_user_V_full_n;
wire   [0:0] corr8_out_V_user_V_dout;
wire    corr8_out_V_user_V_empty_n;
wire    corr8_out_V_last_V_full_n;
wire   [0:0] corr8_out_V_last_V_dout;
wire    corr8_out_V_last_V_empty_n;
wire    corr8_out_V_id_V_full_n;
wire   [0:0] corr8_out_V_id_V_dout;
wire    corr8_out_V_id_V_empty_n;
wire    corr8_out_V_dest_V_full_n;
wire   [0:0] corr8_out_V_dest_V_dout;
wire    corr8_out_V_dest_V_empty_n;
wire   [0:0] start_for_conrr_layer2_U0_din;
wire    start_for_conrr_layer2_U0_full_n;
wire   [0:0] start_for_conrr_layer2_U0_dout;
wire    start_for_conrr_layer2_U0_empty_n;
wire   [0:0] start_for_conrr_layer3_U0_din;
wire    start_for_conrr_layer3_U0_full_n;
wire   [0:0] start_for_conrr_layer3_U0_dout;
wire    start_for_conrr_layer3_U0_empty_n;
wire   [0:0] start_for_conrr_layer4_U0_din;
wire    start_for_conrr_layer4_U0_full_n;
wire   [0:0] start_for_conrr_layer4_U0_dout;
wire    start_for_conrr_layer4_U0_empty_n;
wire   [0:0] start_for_conrr_layer5_U0_din;
wire    start_for_conrr_layer5_U0_full_n;
wire   [0:0] start_for_conrr_layer5_U0_dout;
wire    start_for_conrr_layer5_U0_empty_n;
wire   [0:0] start_for_conrr_layer6_U0_din;
wire    start_for_conrr_layer6_U0_full_n;
wire   [0:0] start_for_conrr_layer6_U0_dout;
wire    start_for_conrr_layer6_U0_empty_n;
wire   [0:0] start_for_conrr_layer7_U0_din;
wire    start_for_conrr_layer7_U0_full_n;
wire   [0:0] start_for_conrr_layer7_U0_dout;
wire    start_for_conrr_layer7_U0_empty_n;
wire   [0:0] start_for_decorr_layer8_U0_din;
wire    start_for_decorr_layer8_U0_full_n;
wire   [0:0] start_for_decorr_layer8_U0_dout;
wire    start_for_decorr_layer8_U0_empty_n;
wire   [0:0] start_for_Loop_1_proc378_U0_din;
wire    start_for_Loop_1_proc378_U0_full_n;
wire   [0:0] start_for_Loop_1_proc378_U0_dout;
wire    start_for_Loop_1_proc378_U0_empty_n;
wire    Loop_1_proc378_U0_start_full_n;
wire    Loop_1_proc378_U0_start_write;

FSRCNN_scalar_parameters_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_SCALAR_PARAMETERS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_SCALAR_PARAMETERS_DATA_WIDTH ))
FSRCNN_scalar_parameters_s_axi_U(
    .AWVALID(s_axi_scalar_parameters_AWVALID),
    .AWREADY(s_axi_scalar_parameters_AWREADY),
    .AWADDR(s_axi_scalar_parameters_AWADDR),
    .WVALID(s_axi_scalar_parameters_WVALID),
    .WREADY(s_axi_scalar_parameters_WREADY),
    .WDATA(s_axi_scalar_parameters_WDATA),
    .WSTRB(s_axi_scalar_parameters_WSTRB),
    .ARVALID(s_axi_scalar_parameters_ARVALID),
    .ARREADY(s_axi_scalar_parameters_ARREADY),
    .ARADDR(s_axi_scalar_parameters_ARADDR),
    .RVALID(s_axi_scalar_parameters_RVALID),
    .RREADY(s_axi_scalar_parameters_RREADY),
    .RDATA(s_axi_scalar_parameters_RDATA),
    .RRESP(s_axi_scalar_parameters_RRESP),
    .BVALID(s_axi_scalar_parameters_BVALID),
    .BREADY(s_axi_scalar_parameters_BREADY),
    .BRESP(s_axi_scalar_parameters_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .height_V(height_V),
    .width_V(width_V),
    .scale_factor_V(scale_factor_V)
);

conrr_layer1 conrr_layer1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conrr_layer1_U0_ap_start),
    .start_full_n(start_for_conrr_layer2_U0_full_n),
    .ap_done(conrr_layer1_U0_ap_done),
    .ap_continue(conrr_layer1_U0_ap_continue),
    .ap_idle(conrr_layer1_U0_ap_idle),
    .ap_ready(conrr_layer1_U0_ap_ready),
    .start_out(conrr_layer1_U0_start_out),
    .start_write(conrr_layer1_U0_start_write),
    .stream_in_TDATA(stream_in_TDATA),
    .stream_in_TVALID(stream_in_TVALID),
    .stream_in_TREADY(conrr_layer1_U0_stream_in_TREADY),
    .stream_in_TKEEP(stream_in_TKEEP),
    .stream_in_TSTRB(stream_in_TSTRB),
    .stream_in_TUSER(stream_in_TUSER),
    .stream_in_TLAST(stream_in_TLAST),
    .stream_in_TID(stream_in_TID),
    .stream_in_TDEST(stream_in_TDEST),
    .corr1_out_V_valid_V_din(conrr_layer1_U0_corr1_out_V_valid_V_din),
    .corr1_out_V_valid_V_full_n(corr1_out_V_valid_V_full_n),
    .corr1_out_V_valid_V_write(conrr_layer1_U0_corr1_out_V_valid_V_write),
    .corr1_out_V_data_V_din(conrr_layer1_U0_corr1_out_V_data_V_din),
    .corr1_out_V_data_V_full_n(corr1_out_V_data_V_full_n),
    .corr1_out_V_data_V_write(conrr_layer1_U0_corr1_out_V_data_V_write),
    .corr1_out_V_keep_V_din(conrr_layer1_U0_corr1_out_V_keep_V_din),
    .corr1_out_V_keep_V_full_n(corr1_out_V_keep_V_full_n),
    .corr1_out_V_keep_V_write(conrr_layer1_U0_corr1_out_V_keep_V_write),
    .corr1_out_V_user_V_din(conrr_layer1_U0_corr1_out_V_user_V_din),
    .corr1_out_V_user_V_full_n(corr1_out_V_user_V_full_n),
    .corr1_out_V_user_V_write(conrr_layer1_U0_corr1_out_V_user_V_write),
    .corr1_out_V_last_V_din(conrr_layer1_U0_corr1_out_V_last_V_din),
    .corr1_out_V_last_V_full_n(corr1_out_V_last_V_full_n),
    .corr1_out_V_last_V_write(conrr_layer1_U0_corr1_out_V_last_V_write),
    .corr1_out_V_id_V_din(conrr_layer1_U0_corr1_out_V_id_V_din),
    .corr1_out_V_id_V_full_n(corr1_out_V_id_V_full_n),
    .corr1_out_V_id_V_write(conrr_layer1_U0_corr1_out_V_id_V_write),
    .corr1_out_V_dest_V_din(conrr_layer1_U0_corr1_out_V_dest_V_din),
    .corr1_out_V_dest_V_full_n(corr1_out_V_dest_V_full_n),
    .corr1_out_V_dest_V_write(conrr_layer1_U0_corr1_out_V_dest_V_write)
);

conrr_layer2 conrr_layer2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conrr_layer2_U0_ap_start),
    .start_full_n(start_for_conrr_layer3_U0_full_n),
    .ap_done(conrr_layer2_U0_ap_done),
    .ap_continue(conrr_layer2_U0_ap_continue),
    .ap_idle(conrr_layer2_U0_ap_idle),
    .ap_ready(conrr_layer2_U0_ap_ready),
    .start_out(conrr_layer2_U0_start_out),
    .start_write(conrr_layer2_U0_start_write),
    .corr1_out_V_valid_V_dout(corr1_out_V_valid_V_dout),
    .corr1_out_V_valid_V_empty_n(corr1_out_V_valid_V_empty_n),
    .corr1_out_V_valid_V_read(conrr_layer2_U0_corr1_out_V_valid_V_read),
    .corr1_out_V_data_V_dout(corr1_out_V_data_V_dout),
    .corr1_out_V_data_V_empty_n(corr1_out_V_data_V_empty_n),
    .corr1_out_V_data_V_read(conrr_layer2_U0_corr1_out_V_data_V_read),
    .corr1_out_V_keep_V_dout(corr1_out_V_keep_V_dout),
    .corr1_out_V_keep_V_empty_n(corr1_out_V_keep_V_empty_n),
    .corr1_out_V_keep_V_read(conrr_layer2_U0_corr1_out_V_keep_V_read),
    .corr1_out_V_user_V_dout(corr1_out_V_user_V_dout),
    .corr1_out_V_user_V_empty_n(corr1_out_V_user_V_empty_n),
    .corr1_out_V_user_V_read(conrr_layer2_U0_corr1_out_V_user_V_read),
    .corr1_out_V_last_V_dout(corr1_out_V_last_V_dout),
    .corr1_out_V_last_V_empty_n(corr1_out_V_last_V_empty_n),
    .corr1_out_V_last_V_read(conrr_layer2_U0_corr1_out_V_last_V_read),
    .corr1_out_V_id_V_dout(corr1_out_V_id_V_dout),
    .corr1_out_V_id_V_empty_n(corr1_out_V_id_V_empty_n),
    .corr1_out_V_id_V_read(conrr_layer2_U0_corr1_out_V_id_V_read),
    .corr1_out_V_dest_V_dout(corr1_out_V_dest_V_dout),
    .corr1_out_V_dest_V_empty_n(corr1_out_V_dest_V_empty_n),
    .corr1_out_V_dest_V_read(conrr_layer2_U0_corr1_out_V_dest_V_read),
    .corr2_out_V_valid_V_din(conrr_layer2_U0_corr2_out_V_valid_V_din),
    .corr2_out_V_valid_V_full_n(corr2_out_V_valid_V_full_n),
    .corr2_out_V_valid_V_write(conrr_layer2_U0_corr2_out_V_valid_V_write),
    .corr2_out_V_data_V_din(conrr_layer2_U0_corr2_out_V_data_V_din),
    .corr2_out_V_data_V_full_n(corr2_out_V_data_V_full_n),
    .corr2_out_V_data_V_write(conrr_layer2_U0_corr2_out_V_data_V_write),
    .corr2_out_V_keep_V_din(conrr_layer2_U0_corr2_out_V_keep_V_din),
    .corr2_out_V_keep_V_full_n(corr2_out_V_keep_V_full_n),
    .corr2_out_V_keep_V_write(conrr_layer2_U0_corr2_out_V_keep_V_write),
    .corr2_out_V_user_V_din(conrr_layer2_U0_corr2_out_V_user_V_din),
    .corr2_out_V_user_V_full_n(corr2_out_V_user_V_full_n),
    .corr2_out_V_user_V_write(conrr_layer2_U0_corr2_out_V_user_V_write),
    .corr2_out_V_last_V_din(conrr_layer2_U0_corr2_out_V_last_V_din),
    .corr2_out_V_last_V_full_n(corr2_out_V_last_V_full_n),
    .corr2_out_V_last_V_write(conrr_layer2_U0_corr2_out_V_last_V_write),
    .corr2_out_V_id_V_din(conrr_layer2_U0_corr2_out_V_id_V_din),
    .corr2_out_V_id_V_full_n(corr2_out_V_id_V_full_n),
    .corr2_out_V_id_V_write(conrr_layer2_U0_corr2_out_V_id_V_write),
    .corr2_out_V_dest_V_din(conrr_layer2_U0_corr2_out_V_dest_V_din),
    .corr2_out_V_dest_V_full_n(corr2_out_V_dest_V_full_n),
    .corr2_out_V_dest_V_write(conrr_layer2_U0_corr2_out_V_dest_V_write)
);

conrr_layer3 conrr_layer3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conrr_layer3_U0_ap_start),
    .start_full_n(start_for_conrr_layer4_U0_full_n),
    .ap_done(conrr_layer3_U0_ap_done),
    .ap_continue(conrr_layer3_U0_ap_continue),
    .ap_idle(conrr_layer3_U0_ap_idle),
    .ap_ready(conrr_layer3_U0_ap_ready),
    .start_out(conrr_layer3_U0_start_out),
    .start_write(conrr_layer3_U0_start_write),
    .corr2_out_V_valid_V_dout(corr2_out_V_valid_V_dout),
    .corr2_out_V_valid_V_empty_n(corr2_out_V_valid_V_empty_n),
    .corr2_out_V_valid_V_read(conrr_layer3_U0_corr2_out_V_valid_V_read),
    .corr2_out_V_data_V_dout(corr2_out_V_data_V_dout),
    .corr2_out_V_data_V_empty_n(corr2_out_V_data_V_empty_n),
    .corr2_out_V_data_V_read(conrr_layer3_U0_corr2_out_V_data_V_read),
    .corr2_out_V_keep_V_dout(corr2_out_V_keep_V_dout),
    .corr2_out_V_keep_V_empty_n(corr2_out_V_keep_V_empty_n),
    .corr2_out_V_keep_V_read(conrr_layer3_U0_corr2_out_V_keep_V_read),
    .corr2_out_V_user_V_dout(corr2_out_V_user_V_dout),
    .corr2_out_V_user_V_empty_n(corr2_out_V_user_V_empty_n),
    .corr2_out_V_user_V_read(conrr_layer3_U0_corr2_out_V_user_V_read),
    .corr2_out_V_last_V_dout(corr2_out_V_last_V_dout),
    .corr2_out_V_last_V_empty_n(corr2_out_V_last_V_empty_n),
    .corr2_out_V_last_V_read(conrr_layer3_U0_corr2_out_V_last_V_read),
    .corr2_out_V_id_V_dout(corr2_out_V_id_V_dout),
    .corr2_out_V_id_V_empty_n(corr2_out_V_id_V_empty_n),
    .corr2_out_V_id_V_read(conrr_layer3_U0_corr2_out_V_id_V_read),
    .corr2_out_V_dest_V_dout(corr2_out_V_dest_V_dout),
    .corr2_out_V_dest_V_empty_n(corr2_out_V_dest_V_empty_n),
    .corr2_out_V_dest_V_read(conrr_layer3_U0_corr2_out_V_dest_V_read),
    .corr3_out_V_valid_V_din(conrr_layer3_U0_corr3_out_V_valid_V_din),
    .corr3_out_V_valid_V_full_n(corr3_out_V_valid_V_full_n),
    .corr3_out_V_valid_V_write(conrr_layer3_U0_corr3_out_V_valid_V_write),
    .corr3_out_V_data_V_din(conrr_layer3_U0_corr3_out_V_data_V_din),
    .corr3_out_V_data_V_full_n(corr3_out_V_data_V_full_n),
    .corr3_out_V_data_V_write(conrr_layer3_U0_corr3_out_V_data_V_write),
    .corr3_out_V_keep_V_din(conrr_layer3_U0_corr3_out_V_keep_V_din),
    .corr3_out_V_keep_V_full_n(corr3_out_V_keep_V_full_n),
    .corr3_out_V_keep_V_write(conrr_layer3_U0_corr3_out_V_keep_V_write),
    .corr3_out_V_user_V_din(conrr_layer3_U0_corr3_out_V_user_V_din),
    .corr3_out_V_user_V_full_n(corr3_out_V_user_V_full_n),
    .corr3_out_V_user_V_write(conrr_layer3_U0_corr3_out_V_user_V_write),
    .corr3_out_V_last_V_din(conrr_layer3_U0_corr3_out_V_last_V_din),
    .corr3_out_V_last_V_full_n(corr3_out_V_last_V_full_n),
    .corr3_out_V_last_V_write(conrr_layer3_U0_corr3_out_V_last_V_write),
    .corr3_out_V_id_V_din(conrr_layer3_U0_corr3_out_V_id_V_din),
    .corr3_out_V_id_V_full_n(corr3_out_V_id_V_full_n),
    .corr3_out_V_id_V_write(conrr_layer3_U0_corr3_out_V_id_V_write),
    .corr3_out_V_dest_V_din(conrr_layer3_U0_corr3_out_V_dest_V_din),
    .corr3_out_V_dest_V_full_n(corr3_out_V_dest_V_full_n),
    .corr3_out_V_dest_V_write(conrr_layer3_U0_corr3_out_V_dest_V_write)
);

conrr_layer4 conrr_layer4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conrr_layer4_U0_ap_start),
    .start_full_n(start_for_conrr_layer5_U0_full_n),
    .ap_done(conrr_layer4_U0_ap_done),
    .ap_continue(conrr_layer4_U0_ap_continue),
    .ap_idle(conrr_layer4_U0_ap_idle),
    .ap_ready(conrr_layer4_U0_ap_ready),
    .start_out(conrr_layer4_U0_start_out),
    .start_write(conrr_layer4_U0_start_write),
    .corr3_out_V_valid_V_dout(corr3_out_V_valid_V_dout),
    .corr3_out_V_valid_V_empty_n(corr3_out_V_valid_V_empty_n),
    .corr3_out_V_valid_V_read(conrr_layer4_U0_corr3_out_V_valid_V_read),
    .corr3_out_V_data_V_dout(corr3_out_V_data_V_dout),
    .corr3_out_V_data_V_empty_n(corr3_out_V_data_V_empty_n),
    .corr3_out_V_data_V_read(conrr_layer4_U0_corr3_out_V_data_V_read),
    .corr3_out_V_keep_V_dout(corr3_out_V_keep_V_dout),
    .corr3_out_V_keep_V_empty_n(corr3_out_V_keep_V_empty_n),
    .corr3_out_V_keep_V_read(conrr_layer4_U0_corr3_out_V_keep_V_read),
    .corr3_out_V_user_V_dout(corr3_out_V_user_V_dout),
    .corr3_out_V_user_V_empty_n(corr3_out_V_user_V_empty_n),
    .corr3_out_V_user_V_read(conrr_layer4_U0_corr3_out_V_user_V_read),
    .corr3_out_V_last_V_dout(corr3_out_V_last_V_dout),
    .corr3_out_V_last_V_empty_n(corr3_out_V_last_V_empty_n),
    .corr3_out_V_last_V_read(conrr_layer4_U0_corr3_out_V_last_V_read),
    .corr3_out_V_id_V_dout(corr3_out_V_id_V_dout),
    .corr3_out_V_id_V_empty_n(corr3_out_V_id_V_empty_n),
    .corr3_out_V_id_V_read(conrr_layer4_U0_corr3_out_V_id_V_read),
    .corr3_out_V_dest_V_dout(corr3_out_V_dest_V_dout),
    .corr3_out_V_dest_V_empty_n(corr3_out_V_dest_V_empty_n),
    .corr3_out_V_dest_V_read(conrr_layer4_U0_corr3_out_V_dest_V_read),
    .corr4_out_V_valid_V_din(conrr_layer4_U0_corr4_out_V_valid_V_din),
    .corr4_out_V_valid_V_full_n(corr4_out_V_valid_V_full_n),
    .corr4_out_V_valid_V_write(conrr_layer4_U0_corr4_out_V_valid_V_write),
    .corr4_out_V_data_V_din(conrr_layer4_U0_corr4_out_V_data_V_din),
    .corr4_out_V_data_V_full_n(corr4_out_V_data_V_full_n),
    .corr4_out_V_data_V_write(conrr_layer4_U0_corr4_out_V_data_V_write),
    .corr4_out_V_keep_V_din(conrr_layer4_U0_corr4_out_V_keep_V_din),
    .corr4_out_V_keep_V_full_n(corr4_out_V_keep_V_full_n),
    .corr4_out_V_keep_V_write(conrr_layer4_U0_corr4_out_V_keep_V_write),
    .corr4_out_V_user_V_din(conrr_layer4_U0_corr4_out_V_user_V_din),
    .corr4_out_V_user_V_full_n(corr4_out_V_user_V_full_n),
    .corr4_out_V_user_V_write(conrr_layer4_U0_corr4_out_V_user_V_write),
    .corr4_out_V_last_V_din(conrr_layer4_U0_corr4_out_V_last_V_din),
    .corr4_out_V_last_V_full_n(corr4_out_V_last_V_full_n),
    .corr4_out_V_last_V_write(conrr_layer4_U0_corr4_out_V_last_V_write),
    .corr4_out_V_id_V_din(conrr_layer4_U0_corr4_out_V_id_V_din),
    .corr4_out_V_id_V_full_n(corr4_out_V_id_V_full_n),
    .corr4_out_V_id_V_write(conrr_layer4_U0_corr4_out_V_id_V_write),
    .corr4_out_V_dest_V_din(conrr_layer4_U0_corr4_out_V_dest_V_din),
    .corr4_out_V_dest_V_full_n(corr4_out_V_dest_V_full_n),
    .corr4_out_V_dest_V_write(conrr_layer4_U0_corr4_out_V_dest_V_write)
);

conrr_layer5 conrr_layer5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conrr_layer5_U0_ap_start),
    .start_full_n(start_for_conrr_layer6_U0_full_n),
    .ap_done(conrr_layer5_U0_ap_done),
    .ap_continue(conrr_layer5_U0_ap_continue),
    .ap_idle(conrr_layer5_U0_ap_idle),
    .ap_ready(conrr_layer5_U0_ap_ready),
    .start_out(conrr_layer5_U0_start_out),
    .start_write(conrr_layer5_U0_start_write),
    .corr4_out_V_valid_V_dout(corr4_out_V_valid_V_dout),
    .corr4_out_V_valid_V_empty_n(corr4_out_V_valid_V_empty_n),
    .corr4_out_V_valid_V_read(conrr_layer5_U0_corr4_out_V_valid_V_read),
    .corr4_out_V_data_V_dout(corr4_out_V_data_V_dout),
    .corr4_out_V_data_V_empty_n(corr4_out_V_data_V_empty_n),
    .corr4_out_V_data_V_read(conrr_layer5_U0_corr4_out_V_data_V_read),
    .corr4_out_V_keep_V_dout(corr4_out_V_keep_V_dout),
    .corr4_out_V_keep_V_empty_n(corr4_out_V_keep_V_empty_n),
    .corr4_out_V_keep_V_read(conrr_layer5_U0_corr4_out_V_keep_V_read),
    .corr4_out_V_user_V_dout(corr4_out_V_user_V_dout),
    .corr4_out_V_user_V_empty_n(corr4_out_V_user_V_empty_n),
    .corr4_out_V_user_V_read(conrr_layer5_U0_corr4_out_V_user_V_read),
    .corr4_out_V_last_V_dout(corr4_out_V_last_V_dout),
    .corr4_out_V_last_V_empty_n(corr4_out_V_last_V_empty_n),
    .corr4_out_V_last_V_read(conrr_layer5_U0_corr4_out_V_last_V_read),
    .corr4_out_V_id_V_dout(corr4_out_V_id_V_dout),
    .corr4_out_V_id_V_empty_n(corr4_out_V_id_V_empty_n),
    .corr4_out_V_id_V_read(conrr_layer5_U0_corr4_out_V_id_V_read),
    .corr4_out_V_dest_V_dout(corr4_out_V_dest_V_dout),
    .corr4_out_V_dest_V_empty_n(corr4_out_V_dest_V_empty_n),
    .corr4_out_V_dest_V_read(conrr_layer5_U0_corr4_out_V_dest_V_read),
    .corr5_out_V_valid_V_din(conrr_layer5_U0_corr5_out_V_valid_V_din),
    .corr5_out_V_valid_V_full_n(corr5_out_V_valid_V_full_n),
    .corr5_out_V_valid_V_write(conrr_layer5_U0_corr5_out_V_valid_V_write),
    .corr5_out_V_data_V_din(conrr_layer5_U0_corr5_out_V_data_V_din),
    .corr5_out_V_data_V_full_n(corr5_out_V_data_V_full_n),
    .corr5_out_V_data_V_write(conrr_layer5_U0_corr5_out_V_data_V_write),
    .corr5_out_V_keep_V_din(conrr_layer5_U0_corr5_out_V_keep_V_din),
    .corr5_out_V_keep_V_full_n(corr5_out_V_keep_V_full_n),
    .corr5_out_V_keep_V_write(conrr_layer5_U0_corr5_out_V_keep_V_write),
    .corr5_out_V_user_V_din(conrr_layer5_U0_corr5_out_V_user_V_din),
    .corr5_out_V_user_V_full_n(corr5_out_V_user_V_full_n),
    .corr5_out_V_user_V_write(conrr_layer5_U0_corr5_out_V_user_V_write),
    .corr5_out_V_last_V_din(conrr_layer5_U0_corr5_out_V_last_V_din),
    .corr5_out_V_last_V_full_n(corr5_out_V_last_V_full_n),
    .corr5_out_V_last_V_write(conrr_layer5_U0_corr5_out_V_last_V_write),
    .corr5_out_V_id_V_din(conrr_layer5_U0_corr5_out_V_id_V_din),
    .corr5_out_V_id_V_full_n(corr5_out_V_id_V_full_n),
    .corr5_out_V_id_V_write(conrr_layer5_U0_corr5_out_V_id_V_write),
    .corr5_out_V_dest_V_din(conrr_layer5_U0_corr5_out_V_dest_V_din),
    .corr5_out_V_dest_V_full_n(corr5_out_V_dest_V_full_n),
    .corr5_out_V_dest_V_write(conrr_layer5_U0_corr5_out_V_dest_V_write)
);

conrr_layer6 conrr_layer6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conrr_layer6_U0_ap_start),
    .start_full_n(start_for_conrr_layer7_U0_full_n),
    .ap_done(conrr_layer6_U0_ap_done),
    .ap_continue(conrr_layer6_U0_ap_continue),
    .ap_idle(conrr_layer6_U0_ap_idle),
    .ap_ready(conrr_layer6_U0_ap_ready),
    .start_out(conrr_layer6_U0_start_out),
    .start_write(conrr_layer6_U0_start_write),
    .corr5_out_V_valid_V_dout(corr5_out_V_valid_V_dout),
    .corr5_out_V_valid_V_empty_n(corr5_out_V_valid_V_empty_n),
    .corr5_out_V_valid_V_read(conrr_layer6_U0_corr5_out_V_valid_V_read),
    .corr5_out_V_data_V_dout(corr5_out_V_data_V_dout),
    .corr5_out_V_data_V_empty_n(corr5_out_V_data_V_empty_n),
    .corr5_out_V_data_V_read(conrr_layer6_U0_corr5_out_V_data_V_read),
    .corr5_out_V_keep_V_dout(corr5_out_V_keep_V_dout),
    .corr5_out_V_keep_V_empty_n(corr5_out_V_keep_V_empty_n),
    .corr5_out_V_keep_V_read(conrr_layer6_U0_corr5_out_V_keep_V_read),
    .corr5_out_V_user_V_dout(corr5_out_V_user_V_dout),
    .corr5_out_V_user_V_empty_n(corr5_out_V_user_V_empty_n),
    .corr5_out_V_user_V_read(conrr_layer6_U0_corr5_out_V_user_V_read),
    .corr5_out_V_last_V_dout(corr5_out_V_last_V_dout),
    .corr5_out_V_last_V_empty_n(corr5_out_V_last_V_empty_n),
    .corr5_out_V_last_V_read(conrr_layer6_U0_corr5_out_V_last_V_read),
    .corr5_out_V_id_V_dout(corr5_out_V_id_V_dout),
    .corr5_out_V_id_V_empty_n(corr5_out_V_id_V_empty_n),
    .corr5_out_V_id_V_read(conrr_layer6_U0_corr5_out_V_id_V_read),
    .corr5_out_V_dest_V_dout(corr5_out_V_dest_V_dout),
    .corr5_out_V_dest_V_empty_n(corr5_out_V_dest_V_empty_n),
    .corr5_out_V_dest_V_read(conrr_layer6_U0_corr5_out_V_dest_V_read),
    .corr6_out_V_valid_V_din(conrr_layer6_U0_corr6_out_V_valid_V_din),
    .corr6_out_V_valid_V_full_n(corr6_out_V_valid_V_full_n),
    .corr6_out_V_valid_V_write(conrr_layer6_U0_corr6_out_V_valid_V_write),
    .corr6_out_V_data_V_din(conrr_layer6_U0_corr6_out_V_data_V_din),
    .corr6_out_V_data_V_full_n(corr6_out_V_data_V_full_n),
    .corr6_out_V_data_V_write(conrr_layer6_U0_corr6_out_V_data_V_write),
    .corr6_out_V_keep_V_din(conrr_layer6_U0_corr6_out_V_keep_V_din),
    .corr6_out_V_keep_V_full_n(corr6_out_V_keep_V_full_n),
    .corr6_out_V_keep_V_write(conrr_layer6_U0_corr6_out_V_keep_V_write),
    .corr6_out_V_user_V_din(conrr_layer6_U0_corr6_out_V_user_V_din),
    .corr6_out_V_user_V_full_n(corr6_out_V_user_V_full_n),
    .corr6_out_V_user_V_write(conrr_layer6_U0_corr6_out_V_user_V_write),
    .corr6_out_V_last_V_din(conrr_layer6_U0_corr6_out_V_last_V_din),
    .corr6_out_V_last_V_full_n(corr6_out_V_last_V_full_n),
    .corr6_out_V_last_V_write(conrr_layer6_U0_corr6_out_V_last_V_write),
    .corr6_out_V_id_V_din(conrr_layer6_U0_corr6_out_V_id_V_din),
    .corr6_out_V_id_V_full_n(corr6_out_V_id_V_full_n),
    .corr6_out_V_id_V_write(conrr_layer6_U0_corr6_out_V_id_V_write),
    .corr6_out_V_dest_V_din(conrr_layer6_U0_corr6_out_V_dest_V_din),
    .corr6_out_V_dest_V_full_n(corr6_out_V_dest_V_full_n),
    .corr6_out_V_dest_V_write(conrr_layer6_U0_corr6_out_V_dest_V_write)
);

conrr_layer7 conrr_layer7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conrr_layer7_U0_ap_start),
    .start_full_n(start_for_decorr_layer8_U0_full_n),
    .ap_done(conrr_layer7_U0_ap_done),
    .ap_continue(conrr_layer7_U0_ap_continue),
    .ap_idle(conrr_layer7_U0_ap_idle),
    .ap_ready(conrr_layer7_U0_ap_ready),
    .start_out(conrr_layer7_U0_start_out),
    .start_write(conrr_layer7_U0_start_write),
    .corr6_out_V_valid_V_dout(corr6_out_V_valid_V_dout),
    .corr6_out_V_valid_V_empty_n(corr6_out_V_valid_V_empty_n),
    .corr6_out_V_valid_V_read(conrr_layer7_U0_corr6_out_V_valid_V_read),
    .corr6_out_V_data_V_dout(corr6_out_V_data_V_dout),
    .corr6_out_V_data_V_empty_n(corr6_out_V_data_V_empty_n),
    .corr6_out_V_data_V_read(conrr_layer7_U0_corr6_out_V_data_V_read),
    .corr6_out_V_keep_V_dout(corr6_out_V_keep_V_dout),
    .corr6_out_V_keep_V_empty_n(corr6_out_V_keep_V_empty_n),
    .corr6_out_V_keep_V_read(conrr_layer7_U0_corr6_out_V_keep_V_read),
    .corr6_out_V_user_V_dout(corr6_out_V_user_V_dout),
    .corr6_out_V_user_V_empty_n(corr6_out_V_user_V_empty_n),
    .corr6_out_V_user_V_read(conrr_layer7_U0_corr6_out_V_user_V_read),
    .corr6_out_V_last_V_dout(corr6_out_V_last_V_dout),
    .corr6_out_V_last_V_empty_n(corr6_out_V_last_V_empty_n),
    .corr6_out_V_last_V_read(conrr_layer7_U0_corr6_out_V_last_V_read),
    .corr6_out_V_id_V_dout(corr6_out_V_id_V_dout),
    .corr6_out_V_id_V_empty_n(corr6_out_V_id_V_empty_n),
    .corr6_out_V_id_V_read(conrr_layer7_U0_corr6_out_V_id_V_read),
    .corr6_out_V_dest_V_dout(corr6_out_V_dest_V_dout),
    .corr6_out_V_dest_V_empty_n(corr6_out_V_dest_V_empty_n),
    .corr6_out_V_dest_V_read(conrr_layer7_U0_corr6_out_V_dest_V_read),
    .corr7_out_V_valid_V_din(conrr_layer7_U0_corr7_out_V_valid_V_din),
    .corr7_out_V_valid_V_full_n(corr7_out_V_valid_V_full_n),
    .corr7_out_V_valid_V_write(conrr_layer7_U0_corr7_out_V_valid_V_write),
    .corr7_out_V_data_V_din(conrr_layer7_U0_corr7_out_V_data_V_din),
    .corr7_out_V_data_V_full_n(corr7_out_V_data_V_full_n),
    .corr7_out_V_data_V_write(conrr_layer7_U0_corr7_out_V_data_V_write),
    .corr7_out_V_keep_V_din(conrr_layer7_U0_corr7_out_V_keep_V_din),
    .corr7_out_V_keep_V_full_n(corr7_out_V_keep_V_full_n),
    .corr7_out_V_keep_V_write(conrr_layer7_U0_corr7_out_V_keep_V_write),
    .corr7_out_V_user_V_din(conrr_layer7_U0_corr7_out_V_user_V_din),
    .corr7_out_V_user_V_full_n(corr7_out_V_user_V_full_n),
    .corr7_out_V_user_V_write(conrr_layer7_U0_corr7_out_V_user_V_write),
    .corr7_out_V_last_V_din(conrr_layer7_U0_corr7_out_V_last_V_din),
    .corr7_out_V_last_V_full_n(corr7_out_V_last_V_full_n),
    .corr7_out_V_last_V_write(conrr_layer7_U0_corr7_out_V_last_V_write),
    .corr7_out_V_id_V_din(conrr_layer7_U0_corr7_out_V_id_V_din),
    .corr7_out_V_id_V_full_n(corr7_out_V_id_V_full_n),
    .corr7_out_V_id_V_write(conrr_layer7_U0_corr7_out_V_id_V_write),
    .corr7_out_V_dest_V_din(conrr_layer7_U0_corr7_out_V_dest_V_din),
    .corr7_out_V_dest_V_full_n(corr7_out_V_dest_V_full_n),
    .corr7_out_V_dest_V_write(conrr_layer7_U0_corr7_out_V_dest_V_write)
);

decorr_layer8 decorr_layer8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(decorr_layer8_U0_ap_start),
    .start_full_n(start_for_Loop_1_proc378_U0_full_n),
    .ap_done(decorr_layer8_U0_ap_done),
    .ap_continue(decorr_layer8_U0_ap_continue),
    .ap_idle(decorr_layer8_U0_ap_idle),
    .ap_ready(decorr_layer8_U0_ap_ready),
    .start_out(decorr_layer8_U0_start_out),
    .start_write(decorr_layer8_U0_start_write),
    .corr7_out_V_valid_V_dout(corr7_out_V_valid_V_dout),
    .corr7_out_V_valid_V_empty_n(corr7_out_V_valid_V_empty_n),
    .corr7_out_V_valid_V_read(decorr_layer8_U0_corr7_out_V_valid_V_read),
    .corr7_out_V_data_V_dout(corr7_out_V_data_V_dout),
    .corr7_out_V_data_V_empty_n(corr7_out_V_data_V_empty_n),
    .corr7_out_V_data_V_read(decorr_layer8_U0_corr7_out_V_data_V_read),
    .corr7_out_V_keep_V_dout(corr7_out_V_keep_V_dout),
    .corr7_out_V_keep_V_empty_n(corr7_out_V_keep_V_empty_n),
    .corr7_out_V_keep_V_read(decorr_layer8_U0_corr7_out_V_keep_V_read),
    .corr7_out_V_user_V_dout(corr7_out_V_user_V_dout),
    .corr7_out_V_user_V_empty_n(corr7_out_V_user_V_empty_n),
    .corr7_out_V_user_V_read(decorr_layer8_U0_corr7_out_V_user_V_read),
    .corr7_out_V_last_V_dout(corr7_out_V_last_V_dout),
    .corr7_out_V_last_V_empty_n(corr7_out_V_last_V_empty_n),
    .corr7_out_V_last_V_read(decorr_layer8_U0_corr7_out_V_last_V_read),
    .corr7_out_V_id_V_dout(corr7_out_V_id_V_dout),
    .corr7_out_V_id_V_empty_n(corr7_out_V_id_V_empty_n),
    .corr7_out_V_id_V_read(decorr_layer8_U0_corr7_out_V_id_V_read),
    .corr7_out_V_dest_V_dout(corr7_out_V_dest_V_dout),
    .corr7_out_V_dest_V_empty_n(corr7_out_V_dest_V_empty_n),
    .corr7_out_V_dest_V_read(decorr_layer8_U0_corr7_out_V_dest_V_read),
    .corr8_out_V_valid_V_din(decorr_layer8_U0_corr8_out_V_valid_V_din),
    .corr8_out_V_valid_V_full_n(corr8_out_V_valid_V_full_n),
    .corr8_out_V_valid_V_write(decorr_layer8_U0_corr8_out_V_valid_V_write),
    .corr8_out_V_data_V_din(decorr_layer8_U0_corr8_out_V_data_V_din),
    .corr8_out_V_data_V_full_n(corr8_out_V_data_V_full_n),
    .corr8_out_V_data_V_write(decorr_layer8_U0_corr8_out_V_data_V_write),
    .corr8_out_V_keep_V_din(decorr_layer8_U0_corr8_out_V_keep_V_din),
    .corr8_out_V_keep_V_full_n(corr8_out_V_keep_V_full_n),
    .corr8_out_V_keep_V_write(decorr_layer8_U0_corr8_out_V_keep_V_write),
    .corr8_out_V_user_V_din(decorr_layer8_U0_corr8_out_V_user_V_din),
    .corr8_out_V_user_V_full_n(corr8_out_V_user_V_full_n),
    .corr8_out_V_user_V_write(decorr_layer8_U0_corr8_out_V_user_V_write),
    .corr8_out_V_last_V_din(decorr_layer8_U0_corr8_out_V_last_V_din),
    .corr8_out_V_last_V_full_n(corr8_out_V_last_V_full_n),
    .corr8_out_V_last_V_write(decorr_layer8_U0_corr8_out_V_last_V_write),
    .corr8_out_V_id_V_din(decorr_layer8_U0_corr8_out_V_id_V_din),
    .corr8_out_V_id_V_full_n(corr8_out_V_id_V_full_n),
    .corr8_out_V_id_V_write(decorr_layer8_U0_corr8_out_V_id_V_write),
    .corr8_out_V_dest_V_din(decorr_layer8_U0_corr8_out_V_dest_V_din),
    .corr8_out_V_dest_V_full_n(corr8_out_V_dest_V_full_n),
    .corr8_out_V_dest_V_write(decorr_layer8_U0_corr8_out_V_dest_V_write)
);

Loop_1_proc378 Loop_1_proc378_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_1_proc378_U0_ap_start),
    .ap_done(Loop_1_proc378_U0_ap_done),
    .ap_continue(Loop_1_proc378_U0_ap_continue),
    .ap_idle(Loop_1_proc378_U0_ap_idle),
    .ap_ready(Loop_1_proc378_U0_ap_ready),
    .corr8_out_V_valid_V_dout(corr8_out_V_valid_V_dout),
    .corr8_out_V_valid_V_empty_n(corr8_out_V_valid_V_empty_n),
    .corr8_out_V_valid_V_read(Loop_1_proc378_U0_corr8_out_V_valid_V_read),
    .corr8_out_V_data_V_dout(corr8_out_V_data_V_dout),
    .corr8_out_V_data_V_empty_n(corr8_out_V_data_V_empty_n),
    .corr8_out_V_data_V_read(Loop_1_proc378_U0_corr8_out_V_data_V_read),
    .corr8_out_V_keep_V_dout(corr8_out_V_keep_V_dout),
    .corr8_out_V_keep_V_empty_n(corr8_out_V_keep_V_empty_n),
    .corr8_out_V_keep_V_read(Loop_1_proc378_U0_corr8_out_V_keep_V_read),
    .corr8_out_V_user_V_dout(corr8_out_V_user_V_dout),
    .corr8_out_V_user_V_empty_n(corr8_out_V_user_V_empty_n),
    .corr8_out_V_user_V_read(Loop_1_proc378_U0_corr8_out_V_user_V_read),
    .corr8_out_V_last_V_dout(corr8_out_V_last_V_dout),
    .corr8_out_V_last_V_empty_n(corr8_out_V_last_V_empty_n),
    .corr8_out_V_last_V_read(Loop_1_proc378_U0_corr8_out_V_last_V_read),
    .corr8_out_V_id_V_dout(corr8_out_V_id_V_dout),
    .corr8_out_V_id_V_empty_n(corr8_out_V_id_V_empty_n),
    .corr8_out_V_id_V_read(Loop_1_proc378_U0_corr8_out_V_id_V_read),
    .corr8_out_V_dest_V_dout(corr8_out_V_dest_V_dout),
    .corr8_out_V_dest_V_empty_n(corr8_out_V_dest_V_empty_n),
    .corr8_out_V_dest_V_read(Loop_1_proc378_U0_corr8_out_V_dest_V_read),
    .stream_out_TDATA(Loop_1_proc378_U0_stream_out_TDATA),
    .stream_out_TVALID(Loop_1_proc378_U0_stream_out_TVALID),
    .stream_out_TREADY(stream_out_TREADY),
    .stream_out_TKEEP(Loop_1_proc378_U0_stream_out_TKEEP),
    .stream_out_TSTRB(Loop_1_proc378_U0_stream_out_TSTRB),
    .stream_out_TUSER(Loop_1_proc378_U0_stream_out_TUSER),
    .stream_out_TLAST(Loop_1_proc378_U0_stream_out_TLAST),
    .stream_out_TID(Loop_1_proc378_U0_stream_out_TID),
    .stream_out_TDEST(Loop_1_proc378_U0_stream_out_TDEST)
);

fifo_w1_d2_A corr1_out_V_valid_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer1_U0_corr1_out_V_valid_V_din),
    .if_full_n(corr1_out_V_valid_V_full_n),
    .if_write(conrr_layer1_U0_corr1_out_V_valid_V_write),
    .if_dout(corr1_out_V_valid_V_dout),
    .if_empty_n(corr1_out_V_valid_V_empty_n),
    .if_read(conrr_layer2_U0_corr1_out_V_valid_V_read)
);

fifo_w12_d2_A corr1_out_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer1_U0_corr1_out_V_data_V_din),
    .if_full_n(corr1_out_V_data_V_full_n),
    .if_write(conrr_layer1_U0_corr1_out_V_data_V_write),
    .if_dout(corr1_out_V_data_V_dout),
    .if_empty_n(corr1_out_V_data_V_empty_n),
    .if_read(conrr_layer2_U0_corr1_out_V_data_V_read)
);

fifo_w4_d2_A corr1_out_V_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer1_U0_corr1_out_V_keep_V_din),
    .if_full_n(corr1_out_V_keep_V_full_n),
    .if_write(conrr_layer1_U0_corr1_out_V_keep_V_write),
    .if_dout(corr1_out_V_keep_V_dout),
    .if_empty_n(corr1_out_V_keep_V_empty_n),
    .if_read(conrr_layer2_U0_corr1_out_V_keep_V_read)
);

fifo_w1_d2_A corr1_out_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer1_U0_corr1_out_V_user_V_din),
    .if_full_n(corr1_out_V_user_V_full_n),
    .if_write(conrr_layer1_U0_corr1_out_V_user_V_write),
    .if_dout(corr1_out_V_user_V_dout),
    .if_empty_n(corr1_out_V_user_V_empty_n),
    .if_read(conrr_layer2_U0_corr1_out_V_user_V_read)
);

fifo_w1_d2_A corr1_out_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer1_U0_corr1_out_V_last_V_din),
    .if_full_n(corr1_out_V_last_V_full_n),
    .if_write(conrr_layer1_U0_corr1_out_V_last_V_write),
    .if_dout(corr1_out_V_last_V_dout),
    .if_empty_n(corr1_out_V_last_V_empty_n),
    .if_read(conrr_layer2_U0_corr1_out_V_last_V_read)
);

fifo_w1_d2_A corr1_out_V_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer1_U0_corr1_out_V_id_V_din),
    .if_full_n(corr1_out_V_id_V_full_n),
    .if_write(conrr_layer1_U0_corr1_out_V_id_V_write),
    .if_dout(corr1_out_V_id_V_dout),
    .if_empty_n(corr1_out_V_id_V_empty_n),
    .if_read(conrr_layer2_U0_corr1_out_V_id_V_read)
);

fifo_w1_d2_A corr1_out_V_dest_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer1_U0_corr1_out_V_dest_V_din),
    .if_full_n(corr1_out_V_dest_V_full_n),
    .if_write(conrr_layer1_U0_corr1_out_V_dest_V_write),
    .if_dout(corr1_out_V_dest_V_dout),
    .if_empty_n(corr1_out_V_dest_V_empty_n),
    .if_read(conrr_layer2_U0_corr1_out_V_dest_V_read)
);

fifo_w1_d2_A corr2_out_V_valid_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer2_U0_corr2_out_V_valid_V_din),
    .if_full_n(corr2_out_V_valid_V_full_n),
    .if_write(conrr_layer2_U0_corr2_out_V_valid_V_write),
    .if_dout(corr2_out_V_valid_V_dout),
    .if_empty_n(corr2_out_V_valid_V_empty_n),
    .if_read(conrr_layer3_U0_corr2_out_V_valid_V_read)
);

fifo_w12_d2_A corr2_out_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer2_U0_corr2_out_V_data_V_din),
    .if_full_n(corr2_out_V_data_V_full_n),
    .if_write(conrr_layer2_U0_corr2_out_V_data_V_write),
    .if_dout(corr2_out_V_data_V_dout),
    .if_empty_n(corr2_out_V_data_V_empty_n),
    .if_read(conrr_layer3_U0_corr2_out_V_data_V_read)
);

fifo_w4_d2_A corr2_out_V_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer2_U0_corr2_out_V_keep_V_din),
    .if_full_n(corr2_out_V_keep_V_full_n),
    .if_write(conrr_layer2_U0_corr2_out_V_keep_V_write),
    .if_dout(corr2_out_V_keep_V_dout),
    .if_empty_n(corr2_out_V_keep_V_empty_n),
    .if_read(conrr_layer3_U0_corr2_out_V_keep_V_read)
);

fifo_w1_d2_A corr2_out_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer2_U0_corr2_out_V_user_V_din),
    .if_full_n(corr2_out_V_user_V_full_n),
    .if_write(conrr_layer2_U0_corr2_out_V_user_V_write),
    .if_dout(corr2_out_V_user_V_dout),
    .if_empty_n(corr2_out_V_user_V_empty_n),
    .if_read(conrr_layer3_U0_corr2_out_V_user_V_read)
);

fifo_w1_d2_A corr2_out_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer2_U0_corr2_out_V_last_V_din),
    .if_full_n(corr2_out_V_last_V_full_n),
    .if_write(conrr_layer2_U0_corr2_out_V_last_V_write),
    .if_dout(corr2_out_V_last_V_dout),
    .if_empty_n(corr2_out_V_last_V_empty_n),
    .if_read(conrr_layer3_U0_corr2_out_V_last_V_read)
);

fifo_w1_d2_A corr2_out_V_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer2_U0_corr2_out_V_id_V_din),
    .if_full_n(corr2_out_V_id_V_full_n),
    .if_write(conrr_layer2_U0_corr2_out_V_id_V_write),
    .if_dout(corr2_out_V_id_V_dout),
    .if_empty_n(corr2_out_V_id_V_empty_n),
    .if_read(conrr_layer3_U0_corr2_out_V_id_V_read)
);

fifo_w1_d2_A corr2_out_V_dest_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer2_U0_corr2_out_V_dest_V_din),
    .if_full_n(corr2_out_V_dest_V_full_n),
    .if_write(conrr_layer2_U0_corr2_out_V_dest_V_write),
    .if_dout(corr2_out_V_dest_V_dout),
    .if_empty_n(corr2_out_V_dest_V_empty_n),
    .if_read(conrr_layer3_U0_corr2_out_V_dest_V_read)
);

fifo_w1_d2_A corr3_out_V_valid_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer3_U0_corr3_out_V_valid_V_din),
    .if_full_n(corr3_out_V_valid_V_full_n),
    .if_write(conrr_layer3_U0_corr3_out_V_valid_V_write),
    .if_dout(corr3_out_V_valid_V_dout),
    .if_empty_n(corr3_out_V_valid_V_empty_n),
    .if_read(conrr_layer4_U0_corr3_out_V_valid_V_read)
);

fifo_w12_d2_A corr3_out_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer3_U0_corr3_out_V_data_V_din),
    .if_full_n(corr3_out_V_data_V_full_n),
    .if_write(conrr_layer3_U0_corr3_out_V_data_V_write),
    .if_dout(corr3_out_V_data_V_dout),
    .if_empty_n(corr3_out_V_data_V_empty_n),
    .if_read(conrr_layer4_U0_corr3_out_V_data_V_read)
);

fifo_w4_d2_A corr3_out_V_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer3_U0_corr3_out_V_keep_V_din),
    .if_full_n(corr3_out_V_keep_V_full_n),
    .if_write(conrr_layer3_U0_corr3_out_V_keep_V_write),
    .if_dout(corr3_out_V_keep_V_dout),
    .if_empty_n(corr3_out_V_keep_V_empty_n),
    .if_read(conrr_layer4_U0_corr3_out_V_keep_V_read)
);

fifo_w1_d2_A corr3_out_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer3_U0_corr3_out_V_user_V_din),
    .if_full_n(corr3_out_V_user_V_full_n),
    .if_write(conrr_layer3_U0_corr3_out_V_user_V_write),
    .if_dout(corr3_out_V_user_V_dout),
    .if_empty_n(corr3_out_V_user_V_empty_n),
    .if_read(conrr_layer4_U0_corr3_out_V_user_V_read)
);

fifo_w1_d2_A corr3_out_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer3_U0_corr3_out_V_last_V_din),
    .if_full_n(corr3_out_V_last_V_full_n),
    .if_write(conrr_layer3_U0_corr3_out_V_last_V_write),
    .if_dout(corr3_out_V_last_V_dout),
    .if_empty_n(corr3_out_V_last_V_empty_n),
    .if_read(conrr_layer4_U0_corr3_out_V_last_V_read)
);

fifo_w1_d2_A corr3_out_V_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer3_U0_corr3_out_V_id_V_din),
    .if_full_n(corr3_out_V_id_V_full_n),
    .if_write(conrr_layer3_U0_corr3_out_V_id_V_write),
    .if_dout(corr3_out_V_id_V_dout),
    .if_empty_n(corr3_out_V_id_V_empty_n),
    .if_read(conrr_layer4_U0_corr3_out_V_id_V_read)
);

fifo_w1_d2_A corr3_out_V_dest_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer3_U0_corr3_out_V_dest_V_din),
    .if_full_n(corr3_out_V_dest_V_full_n),
    .if_write(conrr_layer3_U0_corr3_out_V_dest_V_write),
    .if_dout(corr3_out_V_dest_V_dout),
    .if_empty_n(corr3_out_V_dest_V_empty_n),
    .if_read(conrr_layer4_U0_corr3_out_V_dest_V_read)
);

fifo_w1_d2_A corr4_out_V_valid_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer4_U0_corr4_out_V_valid_V_din),
    .if_full_n(corr4_out_V_valid_V_full_n),
    .if_write(conrr_layer4_U0_corr4_out_V_valid_V_write),
    .if_dout(corr4_out_V_valid_V_dout),
    .if_empty_n(corr4_out_V_valid_V_empty_n),
    .if_read(conrr_layer5_U0_corr4_out_V_valid_V_read)
);

fifo_w12_d2_A corr4_out_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer4_U0_corr4_out_V_data_V_din),
    .if_full_n(corr4_out_V_data_V_full_n),
    .if_write(conrr_layer4_U0_corr4_out_V_data_V_write),
    .if_dout(corr4_out_V_data_V_dout),
    .if_empty_n(corr4_out_V_data_V_empty_n),
    .if_read(conrr_layer5_U0_corr4_out_V_data_V_read)
);

fifo_w4_d2_A corr4_out_V_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer4_U0_corr4_out_V_keep_V_din),
    .if_full_n(corr4_out_V_keep_V_full_n),
    .if_write(conrr_layer4_U0_corr4_out_V_keep_V_write),
    .if_dout(corr4_out_V_keep_V_dout),
    .if_empty_n(corr4_out_V_keep_V_empty_n),
    .if_read(conrr_layer5_U0_corr4_out_V_keep_V_read)
);

fifo_w1_d2_A corr4_out_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer4_U0_corr4_out_V_user_V_din),
    .if_full_n(corr4_out_V_user_V_full_n),
    .if_write(conrr_layer4_U0_corr4_out_V_user_V_write),
    .if_dout(corr4_out_V_user_V_dout),
    .if_empty_n(corr4_out_V_user_V_empty_n),
    .if_read(conrr_layer5_U0_corr4_out_V_user_V_read)
);

fifo_w1_d2_A corr4_out_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer4_U0_corr4_out_V_last_V_din),
    .if_full_n(corr4_out_V_last_V_full_n),
    .if_write(conrr_layer4_U0_corr4_out_V_last_V_write),
    .if_dout(corr4_out_V_last_V_dout),
    .if_empty_n(corr4_out_V_last_V_empty_n),
    .if_read(conrr_layer5_U0_corr4_out_V_last_V_read)
);

fifo_w1_d2_A corr4_out_V_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer4_U0_corr4_out_V_id_V_din),
    .if_full_n(corr4_out_V_id_V_full_n),
    .if_write(conrr_layer4_U0_corr4_out_V_id_V_write),
    .if_dout(corr4_out_V_id_V_dout),
    .if_empty_n(corr4_out_V_id_V_empty_n),
    .if_read(conrr_layer5_U0_corr4_out_V_id_V_read)
);

fifo_w1_d2_A corr4_out_V_dest_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer4_U0_corr4_out_V_dest_V_din),
    .if_full_n(corr4_out_V_dest_V_full_n),
    .if_write(conrr_layer4_U0_corr4_out_V_dest_V_write),
    .if_dout(corr4_out_V_dest_V_dout),
    .if_empty_n(corr4_out_V_dest_V_empty_n),
    .if_read(conrr_layer5_U0_corr4_out_V_dest_V_read)
);

fifo_w1_d2_A corr5_out_V_valid_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer5_U0_corr5_out_V_valid_V_din),
    .if_full_n(corr5_out_V_valid_V_full_n),
    .if_write(conrr_layer5_U0_corr5_out_V_valid_V_write),
    .if_dout(corr5_out_V_valid_V_dout),
    .if_empty_n(corr5_out_V_valid_V_empty_n),
    .if_read(conrr_layer6_U0_corr5_out_V_valid_V_read)
);

fifo_w12_d2_A corr5_out_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer5_U0_corr5_out_V_data_V_din),
    .if_full_n(corr5_out_V_data_V_full_n),
    .if_write(conrr_layer5_U0_corr5_out_V_data_V_write),
    .if_dout(corr5_out_V_data_V_dout),
    .if_empty_n(corr5_out_V_data_V_empty_n),
    .if_read(conrr_layer6_U0_corr5_out_V_data_V_read)
);

fifo_w4_d2_A corr5_out_V_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer5_U0_corr5_out_V_keep_V_din),
    .if_full_n(corr5_out_V_keep_V_full_n),
    .if_write(conrr_layer5_U0_corr5_out_V_keep_V_write),
    .if_dout(corr5_out_V_keep_V_dout),
    .if_empty_n(corr5_out_V_keep_V_empty_n),
    .if_read(conrr_layer6_U0_corr5_out_V_keep_V_read)
);

fifo_w1_d2_A corr5_out_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer5_U0_corr5_out_V_user_V_din),
    .if_full_n(corr5_out_V_user_V_full_n),
    .if_write(conrr_layer5_U0_corr5_out_V_user_V_write),
    .if_dout(corr5_out_V_user_V_dout),
    .if_empty_n(corr5_out_V_user_V_empty_n),
    .if_read(conrr_layer6_U0_corr5_out_V_user_V_read)
);

fifo_w1_d2_A corr5_out_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer5_U0_corr5_out_V_last_V_din),
    .if_full_n(corr5_out_V_last_V_full_n),
    .if_write(conrr_layer5_U0_corr5_out_V_last_V_write),
    .if_dout(corr5_out_V_last_V_dout),
    .if_empty_n(corr5_out_V_last_V_empty_n),
    .if_read(conrr_layer6_U0_corr5_out_V_last_V_read)
);

fifo_w1_d2_A corr5_out_V_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer5_U0_corr5_out_V_id_V_din),
    .if_full_n(corr5_out_V_id_V_full_n),
    .if_write(conrr_layer5_U0_corr5_out_V_id_V_write),
    .if_dout(corr5_out_V_id_V_dout),
    .if_empty_n(corr5_out_V_id_V_empty_n),
    .if_read(conrr_layer6_U0_corr5_out_V_id_V_read)
);

fifo_w1_d2_A corr5_out_V_dest_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer5_U0_corr5_out_V_dest_V_din),
    .if_full_n(corr5_out_V_dest_V_full_n),
    .if_write(conrr_layer5_U0_corr5_out_V_dest_V_write),
    .if_dout(corr5_out_V_dest_V_dout),
    .if_empty_n(corr5_out_V_dest_V_empty_n),
    .if_read(conrr_layer6_U0_corr5_out_V_dest_V_read)
);

fifo_w1_d2_A corr6_out_V_valid_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer6_U0_corr6_out_V_valid_V_din),
    .if_full_n(corr6_out_V_valid_V_full_n),
    .if_write(conrr_layer6_U0_corr6_out_V_valid_V_write),
    .if_dout(corr6_out_V_valid_V_dout),
    .if_empty_n(corr6_out_V_valid_V_empty_n),
    .if_read(conrr_layer7_U0_corr6_out_V_valid_V_read)
);

fifo_w12_d2_A corr6_out_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer6_U0_corr6_out_V_data_V_din),
    .if_full_n(corr6_out_V_data_V_full_n),
    .if_write(conrr_layer6_U0_corr6_out_V_data_V_write),
    .if_dout(corr6_out_V_data_V_dout),
    .if_empty_n(corr6_out_V_data_V_empty_n),
    .if_read(conrr_layer7_U0_corr6_out_V_data_V_read)
);

fifo_w4_d2_A corr6_out_V_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer6_U0_corr6_out_V_keep_V_din),
    .if_full_n(corr6_out_V_keep_V_full_n),
    .if_write(conrr_layer6_U0_corr6_out_V_keep_V_write),
    .if_dout(corr6_out_V_keep_V_dout),
    .if_empty_n(corr6_out_V_keep_V_empty_n),
    .if_read(conrr_layer7_U0_corr6_out_V_keep_V_read)
);

fifo_w1_d2_A corr6_out_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer6_U0_corr6_out_V_user_V_din),
    .if_full_n(corr6_out_V_user_V_full_n),
    .if_write(conrr_layer6_U0_corr6_out_V_user_V_write),
    .if_dout(corr6_out_V_user_V_dout),
    .if_empty_n(corr6_out_V_user_V_empty_n),
    .if_read(conrr_layer7_U0_corr6_out_V_user_V_read)
);

fifo_w1_d2_A corr6_out_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer6_U0_corr6_out_V_last_V_din),
    .if_full_n(corr6_out_V_last_V_full_n),
    .if_write(conrr_layer6_U0_corr6_out_V_last_V_write),
    .if_dout(corr6_out_V_last_V_dout),
    .if_empty_n(corr6_out_V_last_V_empty_n),
    .if_read(conrr_layer7_U0_corr6_out_V_last_V_read)
);

fifo_w1_d2_A corr6_out_V_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer6_U0_corr6_out_V_id_V_din),
    .if_full_n(corr6_out_V_id_V_full_n),
    .if_write(conrr_layer6_U0_corr6_out_V_id_V_write),
    .if_dout(corr6_out_V_id_V_dout),
    .if_empty_n(corr6_out_V_id_V_empty_n),
    .if_read(conrr_layer7_U0_corr6_out_V_id_V_read)
);

fifo_w1_d2_A corr6_out_V_dest_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer6_U0_corr6_out_V_dest_V_din),
    .if_full_n(corr6_out_V_dest_V_full_n),
    .if_write(conrr_layer6_U0_corr6_out_V_dest_V_write),
    .if_dout(corr6_out_V_dest_V_dout),
    .if_empty_n(corr6_out_V_dest_V_empty_n),
    .if_read(conrr_layer7_U0_corr6_out_V_dest_V_read)
);

fifo_w1_d2_A corr7_out_V_valid_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer7_U0_corr7_out_V_valid_V_din),
    .if_full_n(corr7_out_V_valid_V_full_n),
    .if_write(conrr_layer7_U0_corr7_out_V_valid_V_write),
    .if_dout(corr7_out_V_valid_V_dout),
    .if_empty_n(corr7_out_V_valid_V_empty_n),
    .if_read(decorr_layer8_U0_corr7_out_V_valid_V_read)
);

fifo_w12_d2_A corr7_out_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer7_U0_corr7_out_V_data_V_din),
    .if_full_n(corr7_out_V_data_V_full_n),
    .if_write(conrr_layer7_U0_corr7_out_V_data_V_write),
    .if_dout(corr7_out_V_data_V_dout),
    .if_empty_n(corr7_out_V_data_V_empty_n),
    .if_read(decorr_layer8_U0_corr7_out_V_data_V_read)
);

fifo_w4_d2_A corr7_out_V_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer7_U0_corr7_out_V_keep_V_din),
    .if_full_n(corr7_out_V_keep_V_full_n),
    .if_write(conrr_layer7_U0_corr7_out_V_keep_V_write),
    .if_dout(corr7_out_V_keep_V_dout),
    .if_empty_n(corr7_out_V_keep_V_empty_n),
    .if_read(decorr_layer8_U0_corr7_out_V_keep_V_read)
);

fifo_w1_d2_A corr7_out_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer7_U0_corr7_out_V_user_V_din),
    .if_full_n(corr7_out_V_user_V_full_n),
    .if_write(conrr_layer7_U0_corr7_out_V_user_V_write),
    .if_dout(corr7_out_V_user_V_dout),
    .if_empty_n(corr7_out_V_user_V_empty_n),
    .if_read(decorr_layer8_U0_corr7_out_V_user_V_read)
);

fifo_w1_d2_A corr7_out_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer7_U0_corr7_out_V_last_V_din),
    .if_full_n(corr7_out_V_last_V_full_n),
    .if_write(conrr_layer7_U0_corr7_out_V_last_V_write),
    .if_dout(corr7_out_V_last_V_dout),
    .if_empty_n(corr7_out_V_last_V_empty_n),
    .if_read(decorr_layer8_U0_corr7_out_V_last_V_read)
);

fifo_w1_d2_A corr7_out_V_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer7_U0_corr7_out_V_id_V_din),
    .if_full_n(corr7_out_V_id_V_full_n),
    .if_write(conrr_layer7_U0_corr7_out_V_id_V_write),
    .if_dout(corr7_out_V_id_V_dout),
    .if_empty_n(corr7_out_V_id_V_empty_n),
    .if_read(decorr_layer8_U0_corr7_out_V_id_V_read)
);

fifo_w1_d2_A corr7_out_V_dest_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conrr_layer7_U0_corr7_out_V_dest_V_din),
    .if_full_n(corr7_out_V_dest_V_full_n),
    .if_write(conrr_layer7_U0_corr7_out_V_dest_V_write),
    .if_dout(corr7_out_V_dest_V_dout),
    .if_empty_n(corr7_out_V_dest_V_empty_n),
    .if_read(decorr_layer8_U0_corr7_out_V_dest_V_read)
);

fifo_w1_d2_A corr8_out_V_valid_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(decorr_layer8_U0_corr8_out_V_valid_V_din),
    .if_full_n(corr8_out_V_valid_V_full_n),
    .if_write(decorr_layer8_U0_corr8_out_V_valid_V_write),
    .if_dout(corr8_out_V_valid_V_dout),
    .if_empty_n(corr8_out_V_valid_V_empty_n),
    .if_read(Loop_1_proc378_U0_corr8_out_V_valid_V_read)
);

fifo_w12_d2_A corr8_out_V_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(decorr_layer8_U0_corr8_out_V_data_V_din),
    .if_full_n(corr8_out_V_data_V_full_n),
    .if_write(decorr_layer8_U0_corr8_out_V_data_V_write),
    .if_dout(corr8_out_V_data_V_dout),
    .if_empty_n(corr8_out_V_data_V_empty_n),
    .if_read(Loop_1_proc378_U0_corr8_out_V_data_V_read)
);

fifo_w4_d2_A corr8_out_V_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(decorr_layer8_U0_corr8_out_V_keep_V_din),
    .if_full_n(corr8_out_V_keep_V_full_n),
    .if_write(decorr_layer8_U0_corr8_out_V_keep_V_write),
    .if_dout(corr8_out_V_keep_V_dout),
    .if_empty_n(corr8_out_V_keep_V_empty_n),
    .if_read(Loop_1_proc378_U0_corr8_out_V_keep_V_read)
);

fifo_w1_d2_A corr8_out_V_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(decorr_layer8_U0_corr8_out_V_user_V_din),
    .if_full_n(corr8_out_V_user_V_full_n),
    .if_write(decorr_layer8_U0_corr8_out_V_user_V_write),
    .if_dout(corr8_out_V_user_V_dout),
    .if_empty_n(corr8_out_V_user_V_empty_n),
    .if_read(Loop_1_proc378_U0_corr8_out_V_user_V_read)
);

fifo_w1_d2_A corr8_out_V_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(decorr_layer8_U0_corr8_out_V_last_V_din),
    .if_full_n(corr8_out_V_last_V_full_n),
    .if_write(decorr_layer8_U0_corr8_out_V_last_V_write),
    .if_dout(corr8_out_V_last_V_dout),
    .if_empty_n(corr8_out_V_last_V_empty_n),
    .if_read(Loop_1_proc378_U0_corr8_out_V_last_V_read)
);

fifo_w1_d2_A corr8_out_V_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(decorr_layer8_U0_corr8_out_V_id_V_din),
    .if_full_n(corr8_out_V_id_V_full_n),
    .if_write(decorr_layer8_U0_corr8_out_V_id_V_write),
    .if_dout(corr8_out_V_id_V_dout),
    .if_empty_n(corr8_out_V_id_V_empty_n),
    .if_read(Loop_1_proc378_U0_corr8_out_V_id_V_read)
);

fifo_w1_d2_A corr8_out_V_dest_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(decorr_layer8_U0_corr8_out_V_dest_V_din),
    .if_full_n(corr8_out_V_dest_V_full_n),
    .if_write(decorr_layer8_U0_corr8_out_V_dest_V_write),
    .if_dout(corr8_out_V_dest_V_dout),
    .if_empty_n(corr8_out_V_dest_V_empty_n),
    .if_read(Loop_1_proc378_U0_corr8_out_V_dest_V_read)
);

start_for_conrr_lb7t start_for_conrr_lb7t_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conrr_layer2_U0_din),
    .if_full_n(start_for_conrr_layer2_U0_full_n),
    .if_write(conrr_layer1_U0_start_write),
    .if_dout(start_for_conrr_layer2_U0_dout),
    .if_empty_n(start_for_conrr_layer2_U0_empty_n),
    .if_read(conrr_layer2_U0_ap_ready)
);

start_for_conrr_lb8t start_for_conrr_lb8t_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conrr_layer3_U0_din),
    .if_full_n(start_for_conrr_layer3_U0_full_n),
    .if_write(conrr_layer2_U0_start_write),
    .if_dout(start_for_conrr_layer3_U0_dout),
    .if_empty_n(start_for_conrr_layer3_U0_empty_n),
    .if_read(conrr_layer3_U0_ap_ready)
);

start_for_conrr_lb9t start_for_conrr_lb9t_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conrr_layer4_U0_din),
    .if_full_n(start_for_conrr_layer4_U0_full_n),
    .if_write(conrr_layer3_U0_start_write),
    .if_dout(start_for_conrr_layer4_U0_dout),
    .if_empty_n(start_for_conrr_layer4_U0_empty_n),
    .if_read(conrr_layer4_U0_ap_ready)
);

start_for_conrr_lcau start_for_conrr_lcau_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conrr_layer5_U0_din),
    .if_full_n(start_for_conrr_layer5_U0_full_n),
    .if_write(conrr_layer4_U0_start_write),
    .if_dout(start_for_conrr_layer5_U0_dout),
    .if_empty_n(start_for_conrr_layer5_U0_empty_n),
    .if_read(conrr_layer5_U0_ap_ready)
);

start_for_conrr_lcbu start_for_conrr_lcbu_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conrr_layer6_U0_din),
    .if_full_n(start_for_conrr_layer6_U0_full_n),
    .if_write(conrr_layer5_U0_start_write),
    .if_dout(start_for_conrr_layer6_U0_dout),
    .if_empty_n(start_for_conrr_layer6_U0_empty_n),
    .if_read(conrr_layer6_U0_ap_ready)
);

start_for_conrr_lccu start_for_conrr_lccu_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conrr_layer7_U0_din),
    .if_full_n(start_for_conrr_layer7_U0_full_n),
    .if_write(conrr_layer6_U0_start_write),
    .if_dout(start_for_conrr_layer7_U0_dout),
    .if_empty_n(start_for_conrr_layer7_U0_empty_n),
    .if_read(conrr_layer7_U0_ap_ready)
);

start_for_decorr_cdu start_for_decorr_cdu_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_decorr_layer8_U0_din),
    .if_full_n(start_for_decorr_layer8_U0_full_n),
    .if_write(conrr_layer7_U0_start_write),
    .if_dout(start_for_decorr_layer8_U0_dout),
    .if_empty_n(start_for_decorr_layer8_U0_empty_n),
    .if_read(decorr_layer8_U0_ap_ready)
);

start_for_Loop_1_ceu start_for_Loop_1_ceu_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_1_proc378_U0_din),
    .if_full_n(start_for_Loop_1_proc378_U0_full_n),
    .if_write(decorr_layer8_U0_start_write),
    .if_dout(start_for_Loop_1_proc378_U0_dout),
    .if_empty_n(start_for_Loop_1_proc378_U0_empty_n),
    .if_read(Loop_1_proc378_U0_ap_ready)
);

assign Loop_1_proc378_U0_ap_continue = 1'b1;

assign Loop_1_proc378_U0_ap_start = start_for_Loop_1_proc378_U0_empty_n;

assign Loop_1_proc378_U0_start_full_n = 1'b1;

assign Loop_1_proc378_U0_start_write = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign conrr_layer1_U0_ap_continue = 1'b1;

assign conrr_layer1_U0_ap_start = 1'b1;

assign conrr_layer2_U0_ap_continue = 1'b1;

assign conrr_layer2_U0_ap_start = start_for_conrr_layer2_U0_empty_n;

assign conrr_layer3_U0_ap_continue = 1'b1;

assign conrr_layer3_U0_ap_start = start_for_conrr_layer3_U0_empty_n;

assign conrr_layer4_U0_ap_continue = 1'b1;

assign conrr_layer4_U0_ap_start = start_for_conrr_layer4_U0_empty_n;

assign conrr_layer5_U0_ap_continue = 1'b1;

assign conrr_layer5_U0_ap_start = start_for_conrr_layer5_U0_empty_n;

assign conrr_layer6_U0_ap_continue = 1'b1;

assign conrr_layer6_U0_ap_start = start_for_conrr_layer6_U0_empty_n;

assign conrr_layer7_U0_ap_continue = 1'b1;

assign conrr_layer7_U0_ap_start = start_for_conrr_layer7_U0_empty_n;

assign decorr_layer8_U0_ap_continue = 1'b1;

assign decorr_layer8_U0_ap_start = start_for_decorr_layer8_U0_empty_n;

assign start_for_Loop_1_proc378_U0_din = 1'b1;

assign start_for_conrr_layer2_U0_din = 1'b1;

assign start_for_conrr_layer3_U0_din = 1'b1;

assign start_for_conrr_layer4_U0_din = 1'b1;

assign start_for_conrr_layer5_U0_din = 1'b1;

assign start_for_conrr_layer6_U0_din = 1'b1;

assign start_for_conrr_layer7_U0_din = 1'b1;

assign start_for_decorr_layer8_U0_din = 1'b1;

assign stream_in_TREADY = conrr_layer1_U0_stream_in_TREADY;

assign stream_out_TDATA = Loop_1_proc378_U0_stream_out_TDATA;

assign stream_out_TDEST = Loop_1_proc378_U0_stream_out_TDEST;

assign stream_out_TID = Loop_1_proc378_U0_stream_out_TID;

assign stream_out_TKEEP = Loop_1_proc378_U0_stream_out_TKEEP;

assign stream_out_TLAST = Loop_1_proc378_U0_stream_out_TLAST;

assign stream_out_TSTRB = Loop_1_proc378_U0_stream_out_TSTRB;

assign stream_out_TUSER = Loop_1_proc378_U0_stream_out_TUSER;

assign stream_out_TVALID = Loop_1_proc378_U0_stream_out_TVALID;

endmodule //FSRCNN
